import { describe, test, expect } from 'vitest'
import { searchDocsWithTrieve } from './trieve-search'




describe('searchDocsWithTrieve', () => {
    test('returns empty array when no trieveDatasetId provided', async () => {
        const result = await searchDocsWithTrieve({
            query: 'markdown',
            trieveDatasetId: '706c5b23-ec23-46da-bccf-33b6b90a65b3',
        })

        expect(result).toMatchInlineSnapshot(`
          [
            {
              "content": "/essentials/images",
              "id": "page0fc4904a-dcbb-4d56-9ff2-f10023641c07",
              "type": "page",
              "url": "/essentials/images",
            },
            {
              "chunk_html": "Fumabase supports HTML tags in <mark><b>Markdown</b></mark>. This is helpful if you prefer HTML tags to <mark><b>Markdown</b></mark> syntax, and lets you create documentation with infinite flexibility.",
              "content": "Fumabase supports HTML tags in <mark><b>Markdown</b></mark>. This is helpful if you prefer HTML tags to <mark><b>Markdown</b></mark> syntax, and lets you create documentation with infinite flexibility.",
              "created_at": "2025-07-04T07:58:01.149377",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/essentials/images-embeds-and-html-elements-content",
              "image_urls": null,
              "link": "/essentials/images",
              "location": null,
              "metadata": {
                "page_id": "/essentials/images",
                "page_title": "Images and Embeds",
                "section": "Embeds and HTML elements",
                "section_id": "embeds-and-html-elements",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/essentials/images-embeds-and-html-elements-content",
              "type": "text",
              "updated_at": "2025-07-04T07:58:01.149377",
              "url": "/essentials/images#embeds-and-html-elements",
              "weight": 0,
            },
            {
              "chunk_html": "Using <mark><b>Markdown</b></mark>",
              "content": "Using <mark><b>Markdown</b></mark>",
              "created_at": "2025-07-04T07:58:01.149380",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/essentials/images-using-markdown-heading",
              "image_urls": null,
              "link": "/essentials/images",
              "location": null,
              "metadata": {
                "page_id": "/essentials/images",
                "page_title": "Images and Embeds",
                "section": "Using Markdown",
                "section_id": "using-markdown",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/essentials/images-using-markdown-heading",
              "type": "text",
              "updated_at": "2025-07-04T07:58:01.149380",
              "url": "/essentials/images#using-markdown",
              "weight": 0,
            },
            {
              "content": "/-website/react-router-docs/elements",
              "id": "page7dc4594b-b5c6-46af-88d9-4b542a76755c",
              "type": "page",
              "url": "/-website/react-router-docs/elements",
            },
            {
              "chunk_html": "<mark><b>Markdown</b></mark> Elements",
              "content": "<mark><b>Markdown</b></mark> Elements",
              "created_at": "2025-07-02T10:18:58.524579",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/-website/react-router-docs/elements-markdown-elements-heading",
              "image_urls": null,
              "link": "/-website/react-router-docs/elements",
              "location": null,
              "metadata": {
                "page_id": "/-website/react-router-docs/elements",
                "page_title": "Markdown Elements",
                "section": "Markdown Elements",
                "section_id": "markdown-elements",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/-website/react-router-docs/elements-markdown-elements-heading",
              "type": "text",
              "updated_at": "2025-07-02T10:18:58.524579",
              "url": "/-website/react-router-docs/elements#markdown-elements",
              "weight": 0,
            },
            {
              "chunk_html": "This is for testing all the different kinds of <mark><b>markdown</b></mark> that can exist. Whenever I find a styling edge case that exists, I add it to this document. It’s my form of visual regression for all the different kinds of elements that need to be styled across different contexts.",
              "content": "This is for testing all the different kinds of <mark><b>markdown</b></mark> that can exist. Whenever I find a styling edge case that exists, I add it to this document. It’s my form of visual regression for all the different kinds of elements that need to be styled across different contexts.",
              "created_at": "2025-07-02T10:18:58.524510",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/-website/react-router-docs/elements-markdown-elements-content",
              "image_urls": null,
              "link": "/-website/react-router-docs/elements",
              "location": null,
              "metadata": {
                "page_id": "/-website/react-router-docs/elements",
                "page_title": "Markdown Elements",
                "section": "Markdown Elements",
                "section_id": "markdown-elements",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/-website/react-router-docs/elements-markdown-elements-content",
              "type": "text",
              "updated_at": "2025-07-02T10:18:58.524510",
              "url": "/-website/react-router-docs/elements#markdown-elements",
              "weight": 0,
            },
            {
              "content": "/essentials/frontmatter",
              "id": "page4f85ee7f-5fb0-4bc5-b9e4-cab84c2cc8b3",
              "type": "page",
              "url": "/essentials/frontmatter",
            },
            {
              "chunk_html": "Frontmatter is YAML metadata placed at the beginning of your <mark><b>markdown</b></mark> files. It controls how your page is displayed and indexed.",
              "content": "Frontmatter is YAML metadata placed at the beginning of your <mark><b>markdown</b></mark> files. It controls how your page is displayed and indexed.",
              "created_at": "2025-07-04T07:58:01.149348",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/essentials/frontmatter-overview-content",
              "image_urls": null,
              "link": "/essentials/frontmatter",
              "location": null,
              "metadata": {
                "page_id": "/essentials/frontmatter",
                "page_title": "Frontmatter",
                "section": "Overview",
                "section_id": "overview",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/essentials/frontmatter-overview-content",
              "type": "text",
              "updated_at": "2025-07-04T07:58:01.149348",
              "url": "/essentials/frontmatter#overview",
              "weight": 0,
            },
            {
              "content": "/-website/react-router-docs/explanation/special-files",
              "id": "page49f03132-4a65-4fe4-ad97-5c69c2a90cc9",
              "type": "page",
              "url": "/-website/react-router-docs/explanation/special-files",
            },
            {
              "chunk_html": "This file is optional",
              "content": "This file is optional",
              "created_at": "2025-07-02T10:19:00.162718",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/-website/react-router-docs/explanation/special-files-entryservertsx-content",
              "image_urls": null,
              "link": "/-website/react-router-docs/explanation/special-files",
              "location": null,
              "metadata": {
                "page_id": "/-website/react-router-docs/explanation/special-files",
                "page_title": "Special Files",
                "section": "entry.server.tsx",
                "section_id": "entryservertsx",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/-website/react-router-docs/explanation/special-files-entryservertsx-content",
              "type": "text",
              "updated_at": "2025-07-02T10:19:00.162718",
              "url": "/-website/react-router-docs/explanation/special-files#entryservertsx",
              "weight": 0,
            },
            {
              "content": "/-website/react-router-docs/upgrading/component-routes",
              "id": "page780a9f9b-bf15-439f-9e1f-1f6af4fb6b4a",
              "type": "page",
              "url": "/-website/react-router-docs/upgrading/component-routes",
            },
            {
              "chunk_html": "In a typical Vite app, the index.html file is the entry point for bundling. The React Router Vite plugin moves the entry point to a root.tsx file so you can use React to render the shell of your app instead of static HTML, and eventually upgrade to Server Rendering if you want.",
              "content": "In a typical Vite app, the index.html file is the entry point for bundling. The React Router Vite plugin moves the entry point to a root.tsx file so you can use React to render the shell of your app instead of static HTML, and eventually upgrade to Server Rendering if you want.",
              "created_at": "2025-07-02T10:19:06.898692",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/-website/react-router-docs/upgrading/component-routes-3-add-the-root-entry-point-content",
              "image_urls": null,
              "link": "/-website/react-router-docs/upgrading/component-routes",
              "location": null,
              "metadata": {
                "page_id": "/-website/react-router-docs/upgrading/component-routes",
                "page_title": "Framework Adoption from Component Routes",
                "section": "3. Add the Root entry point",
                "section_id": "3-add-the-root-entry-point",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/-website/react-router-docs/upgrading/component-routes-3-add-the-root-entry-point-content",
              "type": "text",
              "updated_at": "2025-07-02T10:19:06.898692",
              "url": "/-website/react-router-docs/upgrading/component-routes#3-add-the-root-entry-point",
              "weight": 0,
            },
            {
              "content": "/-website/react-router-docs/community/contributing",
              "id": "page8b3188e2-1ffa-49a6-98d6-6100f93bc1fe",
              "type": "page",
              "url": "/-website/react-router-docs/community/contributing",
            },
            {
              "chunk_html": "Pull requests need only the approval of two or more collaborators to be merged; when the PR author is a collaborator, that counts as one.",
              "content": "Pull requests need only the approval of two or more collaborators to be merged; when the PR author is a collaborator, that counts as one.",
              "created_at": "2025-07-02T10:18:58.524448",
              "dataset_id": "706c5b23-ec23-46da-bccf-33b6b90a65b3",
              "id": "/-website/react-router-docs/community/contributing-making-a-pull-request-content",
              "image_urls": null,
              "link": "/-website/react-router-docs/community/contributing",
              "location": null,
              "metadata": {
                "page_id": "/-website/react-router-docs/community/contributing",
                "page_title": "Contributing to React Router",
                "section": "Making a Pull Request?",
                "section_id": "making-a-pull-request",
              },
              "num_value": null,
              "tag_set": [],
              "time_stamp": null,
              "tracking_id": "/-website/react-router-docs/community/contributing-making-a-pull-request-content",
              "type": "text",
              "updated_at": "2025-07-02T10:18:58.524448",
              "url": "/-website/react-router-docs/community/contributing#making-a-pull-request",
              "weight": 0,
            },
          ]
        `)
    })
})
