packages:
  - ./*
  - fumadocs/packages/*
  - fumadocs/examples/react-router
  - fumadocs/apps/react-router-18n
  - fumadocs/

autoInstallPeers: false
preferSymlinkedExecutables: true
hoistWorkspacePackages: true

neverBuiltDependencies: []
