// AI Gateway proxy — sits between holocron docs sites and Cloudflare Workers AI.
//
// Exposes an OpenAI-compatible /v1/chat/completions endpoint. User sites call
// this with `@ai-sdk/openai-compatible`. The proxy runs inference via the
// native AI binding (env.AI) routed through CF AI Gateway for logging/analytics,
// and streams the response back in OpenAI SSE format.
//
// After the response is sent, a waitUntil task fetches the AI Gateway log to
// read token count + cost and logs it. This will later deduct from spending caps.
//
// The Env type (including AI: Ai) is generated by `wrangler types` into
// worker-configuration.d.ts. Rerun `wrangler types` after changing wrangler.jsonc.

import { Spiceflow } from 'spiceflow'
import { env, waitUntil } from 'cloudflare:workers'

const AI_GATEWAY_ID = 'holocron'

// Models clients are allowed to request. Keys are the short names clients send
// in the `model` field; values are the full @cf/ model IDs for Workers AI.
// If the client sends an unrecognized model, we fall back to the default.
const ALLOWED_MODELS: Record<string, string> = {
  'glm-4.7-flash': '@cf/zai-org/glm-4.7-flash',
  'qwen3-30b': '@cf/qwen/qwen3-30b-a3b-fp8',
  'llama-3.1-8b': '@cf/meta/llama-3.1-8b-instruct-fast',
  'kimi-k2.5': '@cf/moonshotai/kimi-k2.5',
}

const DEFAULT_MODEL = 'glm-4.7-flash'

function resolveModel(requested?: string): string {
  if (!requested) return ALLOWED_MODELS[DEFAULT_MODEL]!
  if (ALLOWED_MODELS[requested]) return ALLOWED_MODELS[requested]!
  const fullId = Object.values(ALLOWED_MODELS).find((id) => id === requested)
  if (fullId) return fullId
  return ALLOWED_MODELS[DEFAULT_MODEL]!
}

// OpenAI-compatible message — content can be a string or an array of parts
// (tool results, multi-modal content, etc.)
type ChatMessage = {
  role: string
  content: string | unknown[] | null
  tool_calls?: unknown[]
  tool_call_id?: string
  name?: string
}

// Normalize a top-level tool_call from CF Workers AI into OpenAI format.
// CF can return either legacy flat `{ name, arguments }` or already-OpenAI
// `{ id, type, function: { name, arguments } }` at the top level.
function normalizeToolCall(tc: Record<string, unknown>, i: number) {
  const fn = tc.function as Record<string, unknown> | undefined
  if (fn?.name) {
    // Already OpenAI-style
    return {
      id: (tc.id as string) ?? `call_${crypto.randomUUID()}`,
      type: 'function',
      index: i,
      function: {
        name: fn.name as string,
        arguments: typeof fn.arguments === 'string'
          ? fn.arguments
          : JSON.stringify(fn.arguments ?? {}),
      },
    }
  }
  // Legacy flat format
  return {
    id: (tc.id as string) ?? `call_${crypto.randomUUID()}`,
    type: 'function',
    index: i,
    function: {
      name: tc.name as string,
      arguments: typeof tc.arguments === 'string'
        ? tc.arguments
        : JSON.stringify(tc.arguments ?? {}),
    },
  }
}

export const gatewayApp = new Spiceflow()

  // ── OpenAI-compatible chat completions proxy ───────────────────────────
  .post('/api/ai/v1/chat/completions', async ({ request }) => {
    // TODO: Extract and validate holo_xxx API key from Authorization header
    // const apiKey = extractApiKey(request)
    // if (!apiKey) return new Response(JSON.stringify({ error: 'Missing API key' }), { status: 401 })

    // TODO: Check spending cap / rate limit
    // if (record.dollarsUsed >= record.spendingCap) {
    //   return new Response(JSON.stringify({ error: 'Spending limit reached' }), { status: 402 })
    // }

    const body = (await request.json()) as {
      model?: string
      messages?: ChatMessage[]
      stream?: boolean
      temperature?: number
      max_tokens?: number
      tools?: Record<string, unknown>[]
      tool_choice?: unknown
    }

    const modelId = resolveModel(body.model)
    const messages = body.messages || []
    const shouldStream = body.stream !== false

    // Build the inference input, forwarding all supported fields.
    // Tools are passed through in OpenAI format as-is; GLM and other
    // chat-completions models on CF Workers AI expect the wrapped
    // { type: "function", function: { name, description, parameters } } shape.
    const inferenceInput: Record<string, unknown> = {
      messages: messages.map((m) => ({
        role: m.role as 'system' | 'user' | 'assistant' | 'tool',
        content: m.content,
        ...(m.tool_calls ? { tool_calls: m.tool_calls } : {}),
        ...(m.tool_call_id ? { tool_call_id: m.tool_call_id } : {}),
        ...(m.name ? { name: m.name } : {}),
      })),
      stream: shouldStream,
      ...(body.temperature != null ? { temperature: body.temperature } : {}),
      ...(body.max_tokens != null ? { max_tokens: body.max_tokens } : {}),
      ...(body.tools?.length ? { tools: body.tools } : {}),
      ...(body.tool_choice != null ? { tool_choice: body.tool_choice } : {}),
    }

    // Call Workers AI via the native binding, routed through AI Gateway
    const aiResponse = await env.AI.run(
      modelId as Parameters<Ai['run']>[0],
      inferenceInput,
      {
        gateway: {
          id: AI_GATEWAY_ID,
          metadata: {
            model: modelId,
            requestedModel: body.model || DEFAULT_MODEL,
            // TODO: apiKey for per-user tracking
          },
        },
      },
    )

    // Schedule usage logging after the response is sent
    waitUntil(logUsageFromGateway(env.AI))

    const corsHeaders = {
      'access-control-allow-origin': '*',
      'access-control-allow-headers': 'authorization, content-type',
    }

    // env.AI.run() response format varies by model:
    // - Some models (GLM) return full OpenAI chat.completion objects
    // - Some models (Llama) return { response: "text" } legacy format
    // We normalize both to OpenAI format for the client.

    // ── Non-streaming response ────────────────────────────────────────
    if (!shouldStream) {
      const raw = aiResponse as Record<string, unknown>

      // Already in OpenAI format (has choices array)
      if (raw.choices) {
        return Response.json(raw, { headers: corsHeaders })
      }

      // Legacy Workers AI tool_calls format: { tool_calls: [...] }
      // Some CF models return tool_calls at top level instead of inside choices.
      // Handles both flat `{ name, arguments }` and OpenAI-style `{ function: { name, arguments } }`.
      if (Array.isArray(raw.tool_calls)) {
        return Response.json({
          id: `chatcmpl-${crypto.randomUUID()}`,
          object: 'chat.completion',
          created: Math.floor(Date.now() / 1000),
          model: modelId,
          choices: [{
            index: 0,
            message: {
              role: 'assistant',
              content: null,
              tool_calls: (raw.tool_calls as Record<string, unknown>[]).map(normalizeToolCall),
            },
            finish_reason: 'tool_calls',
          }],
          usage: raw.usage || { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
        }, { headers: corsHeaders })
      }

      // Legacy Workers AI format: { response: "text" }
      const text = (raw.response as string) || ''
      return Response.json({
        id: `chatcmpl-${crypto.randomUUID()}`,
        object: 'chat.completion',
        created: Math.floor(Date.now() / 1000),
        model: modelId,
        choices: [{
          index: 0,
          message: { role: 'assistant', content: text },
          finish_reason: 'stop',
        }],
        usage: raw.usage || { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
      }, { headers: corsHeaders })
    }

    // ── Streaming response ────────────────────────────────────────────
    // Both formats stream as ReadableStream. OpenAI-format models send
    // `data: {"choices":[...]}` SSE events; legacy models send
    // `data: {"response":"chunk"}` events. We normalize legacy → OpenAI.
    //
    // SSE events are NOT aligned to ReadableStream chunks, so we keep a
    // carry buffer across reads to handle events split across boundaries.
    const cfStream = aiResponse as ReadableStream<Uint8Array>
    const decoder = new TextDecoder()
    const encoder = new TextEncoder()
    const responseId = `chatcmpl-${crypto.randomUUID()}`
    const created = Math.floor(Date.now() / 1000)

    const sseStream = new ReadableStream({
      async start(controller) {
        const reader = cfStream.getReader()
        let carry = '' // partial line from previous chunk
        try {
          while (true) {
            const { done, value } = await reader.read()
            if (done) break

            carry += decoder.decode(value, { stream: true })
            const parts = carry.split('\n')
            // Last element may be incomplete; keep it for next iteration
            carry = parts.pop() ?? ''

            for (const line of parts) {
              if (!line.startsWith('data: ')) continue
              const payload = line.slice(6).trim()

              if (payload === '[DONE]') {
                controller.enqueue(encoder.encode('data: [DONE]\n\n'))
                continue
              }

              try {
                const parsed = JSON.parse(payload)

                // Already OpenAI format (has choices array)
                if (parsed.choices) {
                  controller.enqueue(encoder.encode(`data: ${payload}\n\n`))
                  continue
                }

                // Legacy format: { response: "chunk" }
                if (parsed.response !== undefined) {
                  const chunk = JSON.stringify({
                    id: responseId,
                    object: 'chat.completion.chunk',
                    created,
                    model: modelId,
                    choices: [{
                      index: 0,
                      delta: { content: parsed.response },
                      finish_reason: null,
                    }],
                  })
                  controller.enqueue(encoder.encode(`data: ${chunk}\n\n`))
                  continue
                }

                // Legacy streamed tool_calls: { tool_calls: [...] }
                if (Array.isArray(parsed.tool_calls)) {
                  const chunk = JSON.stringify({
                    id: responseId,
                    object: 'chat.completion.chunk',
                    created,
                    model: modelId,
                    choices: [{
                      index: 0,
                      delta: {
                        tool_calls: (parsed.tool_calls as Record<string, unknown>[]).map(normalizeToolCall),
                      },
                      finish_reason: null,
                    }],
                  })
                  controller.enqueue(encoder.encode(`data: ${chunk}\n\n`))
                }
              } catch {
                // Incomplete JSON or non-data line, skip
              }
            }
          }

          // Flush any remaining carry (e.g. final [DONE] without trailing newline)
          if (carry.startsWith('data: ')) {
            const payload = carry.slice(6).trim()
            if (payload === '[DONE]') {
              controller.enqueue(encoder.encode('data: [DONE]\n\n'))
            }
          }
        } finally {
          reader.releaseLock()
          controller.close()
        }
      },
    })

    return new Response(sseStream, {
      headers: {
        ...corsHeaders,
        'content-type': 'text/event-stream',
        'cache-control': 'no-cache',
        'connection': 'keep-alive',
      },
    })
  })

  // ── CORS preflight for the AI proxy ────────────────────────────────────
  .get('/api/ai/v1/chat/completions', () => {
    return new Response(null, {
      status: 204,
      headers: {
        'access-control-allow-origin': '*',
        'access-control-allow-methods': 'POST, OPTIONS',
        'access-control-allow-headers': 'authorization, content-type',
      },
    })
  })

  // ── List available models ──────────────────────────────────────────────
  .get('/api/ai/v1/models', () => {
    const models = Object.entries(ALLOWED_MODELS).map(([name, id]) => ({
      id: name,
      object: 'model' as const,
      created: 0,
      owned_by: 'cloudflare',
      _cf_model_id: id,
    }))
    return Response.json({ object: 'list', data: models })
  })

// ── Usage logging via AI Gateway ─────────────────────────────────────────

async function logUsageFromGateway(ai: Ai) {
  try {
    const logId = ai.aiGatewayLogId
    if (!logId) {
      console.warn('[gateway] No AI Gateway log ID available')
      return
    }

    const gateway = ai.gateway(AI_GATEWAY_ID)
    const log = await gateway.getLog(logId)

    console.log('[gateway] usage', JSON.stringify({
      logId,
      model: log.model,
      provider: log.provider,
      tokensIn: log.tokens_in,
      tokensOut: log.tokens_out,
      cost: log.cost,
      duration: log.duration,
      status: log.status_code,
    }))

    // TODO: Deduct cost from user's spending cap in KV
    // if (log.cost && apiKey) {
    //   await kv.incrementUsage(apiKey, log.cost)
    // }
  } catch (err) {
    console.warn('[gateway] failed to fetch usage log:', err)
  }
}

// TODO: Stripe checkout, webhook, usage, status, cancel, plans endpoints
// TODO: KV storage for API keys, usage tracking, subscriptions
// See egaki gateway (egaki/gateway/src/kv.ts) for the pattern
