'use client'

/**
 * ChatHost — light-DOM container for the standalone chat widget.
 *
 * Renders children inside a `.holocron-chat` div and injects the compiled
 * chat CSS (scoped under `.holocron-chat` at build time) into document.head.
 *
 * Why light DOM instead of shadow DOM: Chrome ignores `view-transition-name`
 * on elements inside shadow roots — only light-DOM elements are captured into
 * the document's view transition pseudo tree. The pill → drawer morph (and
 * any future VT) therefore requires the widget to live in the page's light
 * DOM, exactly like the docs-mode sidebar assistant + drawer.
 *
 * Style isolation is preserved by the build-time scoping in
 * scripts/bundle-chat-css.ts: preflight, utilities, and component styles are
 * all prefixed with `.holocron-chat`, so nothing leaks into the host page.
 * CSS custom properties on the container (or any ancestor) theme the widget.
 */

import React, { useLayoutEffect, useRef } from 'react'

// Combined CSS (Tailwind utilities + chat.css) as a string constant,
// scoped under .holocron-chat. Generated by scripts/bundle-chat-css.ts.
import { chatCssBundle } from './chat-css-bundle.ts'

const STYLE_ATTR = 'data-holocron-chat'

export function ChatHost({
  children,
  className,
  style,
  dark,
  onMountPoint,
}: {
  children: React.ReactNode
  className?: string
  style?: React.CSSProperties
  /** When true, applies the .dark class to the container for dark mode. */
  dark?: boolean
  /** Called with the container element once mounted.
   *  Use this to set the portal target in chatWidgetStore. */
  onMountPoint?: (mount: HTMLElement) => void
}) {
  const containerRef = useRef<HTMLDivElement>(null)

  useLayoutEffect(() => {
    // Inject CSS once per document
    if (!document.head.querySelector(`style[${STYLE_ATTR}]`)) {
      const styleEl = document.createElement('style')
      styleEl.setAttribute(STYLE_ATTR, '')
      styleEl.textContent = chatCssBundle
      document.head.appendChild(styleEl)
    }
    if (containerRef.current) {
      onMountPoint?.(containerRef.current)
    }
  }, [onMountPoint])

  return (
    <div
      ref={containerRef}
      className={`holocron-chat${dark ? ' dark' : ''} ${className || ''}`}
      style={style}
      data-holocron-chat-host=''
    >
      {children}
    </div>
  )
}
