/**
 * Mock runtime provider for testing. Returns hardcoded guides
 * with nested navigation groups.
 */

import type { CustomTabProvider } from '@holocron.so/vite'

const provider: CustomTabProvider = {
  name: 'mock-guides',
  static: false,
  ttlMs: 10_000, // 10s for dev testing

  async generate({ tab }) {
    const base = tab.base ?? 'guides'

    const mdxContent: Record<string, string> = {
      [`${base}/getting-started`]: [
        '---',
        'title: "Getting Started"',
        'description: "Your first steps with the platform"',
        '---',
        '',
        '# Getting Started',
        '',
        'Welcome to the **Getting Started** guide. This page was generated by a runtime provider.',
        '',
        '## Installation',
        '',
        '```bash',
        'npm install my-package',
        '```',
        '',
        '## Quick Example',
        '',
        '```ts',
        'import { create } from "my-package"',
        '',
        'const app = create({ name: "hello" })',
        'app.start()',
        '```',
      ].join('\n'),

      [`${base}/configuration`]: [
        '---',
        'title: "Configuration"',
        'description: "Configure your project settings"',
        '---',
        '',
        '# Configuration',
        '',
        'All configuration is done via `config.json` at the project root.',
        '',
        '| Option | Type | Default | Description |',
        '|--------|------|---------|-------------|',
        '| `name` | string | `""` | Project name |',
        '| `port` | number | `3000` | Server port |',
        '| `debug` | boolean | `false` | Enable debug logging |',
      ].join('\n'),

      [`${base}/advanced/plugins`]: [
        '---',
        'title: "Plugins"',
        'description: "Extend functionality with plugins"',
        '---',
        '',
        '# Plugins',
        '',
        'The plugin system lets you extend the core with custom behavior.',
        '',
        '```ts',
        'import { definePlugin } from "my-package/plugins"',
        '',
        'export default definePlugin({',
        '  name: "my-plugin",',
        '  setup(app) {',
        '    app.on("request", (req) => {',
        '      console.log("incoming:", req.url)',
        '    })',
        '  },',
        '})',
        '```',
      ].join('\n'),

      [`${base}/advanced/deployment`]: [
        '---',
        'title: "Deployment"',
        'description: "Deploy to production"',
        '---',
        '',
        '# Deployment',
        '',
        'Deploy your app to any cloud provider.',
        '',
        '## Docker',
        '',
        '```dockerfile',
        'FROM node:22-slim',
        'WORKDIR /app',
        'COPY . .',
        'RUN npm ci && npm run build',
        'CMD ["npm", "start"]',
        '```',
      ].join('\n'),
    }

    return {
      groups: [
        {
          group: 'Basics',
          pages: [`${base}/getting-started`, `${base}/configuration`],
        },
        {
          group: 'Advanced',
          pages: [`${base}/advanced/plugins`, `${base}/advanced/deployment`],
        },
      ],
      mdxContent,
    }
  },
}

export default provider
