// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6ea1ba37e05fac32 "Fumabase website, made from Aset", do not edit manually */
"use client";

/**
 * @typedef Locale
 * A string that represents the locale.
 */

/**
 * @typedef Props
 * @property {React.ReactNode} [children] - The children components.
 * @property {Locale} [locale] - The active locale.
 * @property {React.CSSProperties} [style] - The component styles.
 * @property {string} [className] - Additional class names for the component.
 * @property {string} [id] - The component id.
 * @property {*} [width] - The component width.
 * @property {*} [height] - The component height.
 * @property {string} [layoutId] - The layout id.
 * @property {'Desktop' | 'Tablet' | 'Phone'} [variant] - Variant
 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-WESH6F3M.js";
import "./chunks/chunk-KRWE7EDW.js";
import "./chunks/chunk-WLP5URBW.js";
import "./chunks/chunk-BTSBQWPZ.js";
import { className, css, fonts } from "./chunks/chunk-KYATNZPG.js";
import { stdin_default } from "./chunks/chunk-EHCTMXQN.js";
import { routes } from "./chunks/chunk-GECJBHKX.js";

// virtual:benefit-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jXKnJfWfJ6CmOI4Pa51Y/ZjaKzR7MQeAAUpQ9s7QR/uSzRf2WyT.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFX = withFX(RichText);
var MotionDivWithFX = withFX(motion.div);
var BenefitCardFonts = getFonts(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var GridFonts = getFonts(stdin_default);
var cycleOrder = ["zISvybPEk", "C_ZZDts2y", "GFIhwxsh9"];
var serializationHash = "framer-7G6fC";
var variantClassNames = {
	C_ZZDts2y: "framer-v-tvkrgq",
	GFIhwxsh9: "framer-v-hh5j7x",
	zISvybPEk: "framer-v-1vlqip2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 80,
};
var transition2 = {
	bounce: 0.1,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 50,
};
var transition3 = {
	bounce: 0.1,
	delay: 0.1,
	duration: 0.8,
	type: "spring",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.7,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 50,
};
var transition4 = {
	bounce: 0.1,
	delay: 0.2,
	duration: 0.8,
	type: "spring",
};
var transition5 = {
	bounce: 0.1,
	delay: 0.3,
	duration: 0.8,
	type: "spring",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.9,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 50,
};
var transition6 = {
	bounce: 0.1,
	delay: 0.4,
	duration: 0.8,
	type: "spring",
};
var transition7 = {
	bounce: 0.1,
	delay: 0.5,
	duration: 0.8,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "zISvybPEk",
	Phone: "GFIhwxsh9",
	Tablet: "C_ZZDts2y",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zISvybPEk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zISvybPEk",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1vlqip2",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"zISvybPEk"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							...style,
						}}
						variants={{
							GFIhwxsh9: {
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
							},
						}}
						{...addPropertyOverrides(
							{
								C_ZZDts2y: {
									"data-framer-name": "Tablet",
								},
								GFIhwxsh9: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-uzoqzu"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"asWySC6Qt"}
						>
							<motion.div
								className={"framer-10uv332"}
								data-framer-name={"Heading Content"}
								layoutDependency={layoutDependency}
								layoutId={"c2w02LtMV"}
							>
								<motion.div
									className={"framer-1xv11j0"}
									data-framer-name={"Container"}
									layoutDependency={layoutDependency}
									layoutId={"EYXbWAQ1J"}
								>
									<MotionDivWithFX
										className={"framer-w9tee5"}
										data-framer-name={"Heading"}
										layoutDependency={layoutDependency}
										layoutId={"QXx4FogCB"}
										{...addPropertyOverrides(
											{
												GFIhwxsh9: {
													__framer__animate: {
														transition: transition2,
													},
													__framer__animateOnce: true,
													__framer__enter: animation,
													__framer__styleAppearEffectEnabled: true,
													__framer__threshold: 0,
													__perspectiveFX: false,
													__smartComponentFX: true,
													__targetOpacity: 1,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<RichTextWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation1}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1gd1sx2"}
											data-framer-name={"Heading"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"qiPwHf7Ky"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													GFIhwxsh9: {
														__framer__styleAppearEffectEnabled: void 0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.h2
													className={"framer-styles-preset-163xgy6"}
													data-styles-preset={"EEpMe6lZZ"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"Smarter Investing. "}
													<motion.br />
													{"Stronger Outcomes"}
												</motion.h2>
											</React.Fragment>
										</RichTextWithFX>
									</MotionDivWithFX>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-11cgjwm"}
								data-framer-name={"Card"}
								layoutDependency={layoutDependency}
								layoutId={"mDudIZrfg"}
							>
								<ComponentViewportProvider
									height={170}
									width={`max((min(${componentViewport?.width || "100vw"} - 200px, 1100px) - 30px) / 3, 50px)`}
									y={
										(componentViewport?.y || 0) +
										200 +
										(((componentViewport?.height || 722) - 250 - 426.2) / 2 +
											0 +
											0) +
										0 +
										71.2 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											C_ZZDts2y: {
												width: `max((min(min(${componentViewport?.width || "100vw"} - 80px, 1100px), 810px) - 15px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													150 +
													(((componentViewport?.height || 847) - 190 - 611.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													0,
											},
											GFIhwxsh9: {
												width: `max(min(min(${componentViewport?.width || "100vw"} - 40px, 1100px), 600px), 50px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1400) -
														120 -
														1141.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition2,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-yq5mik-container"}
										layoutDependency={layoutDependency}
										layoutId={"NjrcSoQxz-container"}
										nodeId={"NjrcSoQxz"}
										rendersWithMotion={true}
										scopeId={"uSzRf2WyT"}
										{...addPropertyOverrides(
											{
												GFIhwxsh9: {
													__framer__enter: animation,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{_jsx(stdin_default2, {
											e2KlnzxYz: "AI-Powered Strategies",
											Ec4tMUtI0:
												"Adaptive strategies driven by real-time machine learning.",
											height: "100%",
											id: "NjrcSoQxz",
											layoutId: "NjrcSoQxz",
											QT_GTeY8Q: "ChartLineUp",
											style: {
												width: "100%",
											},
											variant: "i0XLBMf50",
											width: "100%",
											...addPropertyOverrides(
												{
													C_ZZDts2y: {
														e2KlnzxYz: "Real-Time Insights",
														Ec4tMUtI0:
															"Access blockchain data in real-time to make timely and informed decisions.",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={170}
									width={`max((min(${componentViewport?.width || "100vw"} - 200px, 1100px) - 30px) / 3, 50px)`}
									y={
										(componentViewport?.y || 0) +
										200 +
										(((componentViewport?.height || 722) - 250 - 426.2) / 2 +
											0 +
											0) +
										0 +
										71.2 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											C_ZZDts2y: {
												width: `max((min(min(${componentViewport?.width || "100vw"} - 80px, 1100px), 810px) - 15px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													150 +
													(((componentViewport?.height || 847) - 190 - 611.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													0,
											},
											GFIhwxsh9: {
												width: `max(min(min(${componentViewport?.width || "100vw"} - 40px, 1100px), 600px), 50px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1400) -
														120 -
														1141.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													180,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition3,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-cuu991-container"}
										layoutDependency={layoutDependency}
										layoutId={"rwuszWyOa-container"}
										nodeId={"rwuszWyOa"}
										rendersWithMotion={true}
										scopeId={"uSzRf2WyT"}
										{...addPropertyOverrides(
											{
												GFIhwxsh9: {
													__framer__animate: {
														transition: transition2,
													},
													__framer__enter: animation,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{_jsx(stdin_default2, {
											e2KlnzxYz: "Portfolio Optimization",
											Ec4tMUtI0:
												"Smart rebalancing to maximize returns and control risk effectively.",
											height: "100%",
											id: "rwuszWyOa",
											layoutId: "rwuszWyOa",
											QT_GTeY8Q: "ChartDonut",
											style: {
												width: "100%",
											},
											variant: "i0XLBMf50",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={170}
									width={`max((min(${componentViewport?.width || "100vw"} - 200px, 1100px) - 30px) / 3, 50px)`}
									y={
										(componentViewport?.y || 0) +
										200 +
										(((componentViewport?.height || 722) - 250 - 426.2) / 2 +
											0 +
											0) +
										0 +
										71.2 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											C_ZZDts2y: {
												width: `max((min(min(${componentViewport?.width || "100vw"} - 80px, 1100px), 810px) - 15px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													150 +
													(((componentViewport?.height || 847) - 190 - 611.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													185,
											},
											GFIhwxsh9: {
												width: `max(min(min(${componentViewport?.width || "100vw"} - 40px, 1100px), 600px), 50px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1400) -
														120 -
														1141.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													360,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition4,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-xbvzy9-container"}
										layoutDependency={layoutDependency}
										layoutId={"iGG3ubzmv-container"}
										nodeId={"iGG3ubzmv"}
										rendersWithMotion={true}
										scopeId={"uSzRf2WyT"}
										{...addPropertyOverrides(
											{
												GFIhwxsh9: {
													__framer__animate: {
														transition: transition2,
													},
													__framer__enter: animation,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{_jsx(stdin_default2, {
											e2KlnzxYz: "Real-Time Insights",
											Ec4tMUtI0:
												"Live analytics provide clarity for every investment decision.",
											height: "100%",
											id: "iGG3ubzmv",
											layoutId: "iGG3ubzmv",
											QT_GTeY8Q: "ChartScatter",
											style: {
												width: "100%",
											},
											variant: "i0XLBMf50",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={170}
									width={`max((min(${componentViewport?.width || "100vw"} - 200px, 1100px) - 30px) / 3, 50px)`}
									y={
										(componentViewport?.y || 0) +
										200 +
										(((componentViewport?.height || 722) - 250 - 426.2) / 2 +
											0 +
											0) +
										0 +
										71.2 +
										0 +
										185
									}
									{...addPropertyOverrides(
										{
											C_ZZDts2y: {
												width: `max((min(min(${componentViewport?.width || "100vw"} - 80px, 1100px), 810px) - 15px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													150 +
													(((componentViewport?.height || 847) - 190 - 611.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													185,
											},
											GFIhwxsh9: {
												width: `max(min(min(${componentViewport?.width || "100vw"} - 40px, 1100px), 600px), 50px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1400) -
														120 -
														1141.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													540,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition5,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1rn7ipq-container"}
										layoutDependency={layoutDependency}
										layoutId={"bW_HOgte1-container"}
										nodeId={"bW_HOgte1"}
										rendersWithMotion={true}
										scopeId={"uSzRf2WyT"}
										{...addPropertyOverrides(
											{
												GFIhwxsh9: {
													__framer__animate: {
														transition: transition2,
													},
													__framer__enter: animation,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{_jsx(stdin_default2, {
											e2KlnzxYz: "Automated Execution",
											Ec4tMUtI0:
												"Seamless execution from signal to trade, with precision and speed.",
											height: "100%",
											id: "bW_HOgte1",
											layoutId: "bW_HOgte1",
											QT_GTeY8Q: "CirclesFour",
											style: {
												width: "100%",
											},
											variant: "i0XLBMf50",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={170}
									width={`max((min(${componentViewport?.width || "100vw"} - 200px, 1100px) - 30px) / 3, 50px)`}
									y={
										(componentViewport?.y || 0) +
										200 +
										(((componentViewport?.height || 722) - 250 - 426.2) / 2 +
											0 +
											0) +
										0 +
										71.2 +
										0 +
										185
									}
									{...addPropertyOverrides(
										{
											C_ZZDts2y: {
												width: `max((min(min(${componentViewport?.width || "100vw"} - 80px, 1100px), 810px) - 15px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													150 +
													(((componentViewport?.height || 847) - 190 - 611.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													370,
											},
											GFIhwxsh9: {
												width: `max(min(min(${componentViewport?.width || "100vw"} - 40px, 1100px), 600px), 50px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1400) -
														120 -
														1141.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													720,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition6,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation3}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-17r2tkd-container"}
										layoutDependency={layoutDependency}
										layoutId={"QMCfI5Sdn-container"}
										nodeId={"QMCfI5Sdn"}
										rendersWithMotion={true}
										scopeId={"uSzRf2WyT"}
										{...addPropertyOverrides(
											{
												GFIhwxsh9: {
													__framer__animate: {
														transition: transition2,
													},
													__framer__enter: animation,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{_jsx(stdin_default2, {
											e2KlnzxYz: "Adaptive Risk Management",
											Ec4tMUtI0:
												"AI models adjust exposure based on changing market dynamics and volatility.",
											height: "100%",
											id: "QMCfI5Sdn",
											layoutId: "QMCfI5Sdn",
											QT_GTeY8Q: "Circuitry",
											style: {
												width: "100%",
											},
											variant: "i0XLBMf50",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={170}
									width={`max((min(${componentViewport?.width || "100vw"} - 200px, 1100px) - 30px) / 3, 50px)`}
									y={
										(componentViewport?.y || 0) +
										200 +
										(((componentViewport?.height || 722) - 250 - 426.2) / 2 +
											0 +
											0) +
										0 +
										71.2 +
										0 +
										185
									}
									{...addPropertyOverrides(
										{
											C_ZZDts2y: {
												width: `max((min(min(${componentViewport?.width || "100vw"} - 80px, 1100px), 810px) - 15px) / 2, 50px)`,
												y:
													(componentViewport?.y || 0) +
													150 +
													(((componentViewport?.height || 847) - 190 - 611.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													370,
											},
											GFIhwxsh9: {
												width: `max(min(min(${componentViewport?.width || "100vw"} - 40px, 1100px), 600px), 50px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1400) -
														120 -
														1141.2) /
														2 +
														0 +
														0) +
													0 +
													71.2 +
													0 +
													900,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainerWithFX
										__framer__animate={{
											transition: transition7,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation3}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-1h3xmn-container"}
										layoutDependency={layoutDependency}
										layoutId={"Jp0PD1z46-container"}
										nodeId={"Jp0PD1z46"}
										rendersWithMotion={true}
										scopeId={"uSzRf2WyT"}
										{...addPropertyOverrides(
											{
												GFIhwxsh9: {
													__framer__animate: {
														transition: transition2,
													},
													__framer__enter: animation,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										{_jsx(stdin_default2, {
											e2KlnzxYz: "Performance Tracking",
											Ec4tMUtI0:
												"Monitor performance in real-time with clear metrics and visual reporting.",
											height: "100%",
											id: "Jp0PD1z46",
											layoutId: "Jp0PD1z46",
											QT_GTeY8Q: "Cube",
											style: {
												width: "100%",
											},
											variant: "i0XLBMf50",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFX>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-i4a7x7"}
							data-framer-name={"Grid"}
							layoutDependency={layoutDependency}
							layoutId={"WyGg344YA"}
						>
							<ComponentViewportProvider
								height={(componentViewport?.height || 722) * 1 * 1}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									((componentViewport?.height || 722) * 0.5000000000000002 -
										((componentViewport?.height || 722) * 1) / 2) +
									0
								}
								{...addPropertyOverrides(
									{
										C_ZZDts2y: {
											height: (componentViewport?.height || 847) * 1 * 1,
											y:
												(componentViewport?.y || 0) +
												((componentViewport?.height || 847) *
													0.5000000000000002 -
													((componentViewport?.height || 847) * 1) / 2) +
												0,
										},
										GFIhwxsh9: {
											height: (componentViewport?.height || 1400) * 1 * 1,
											y:
												(componentViewport?.y || 0) +
												((componentViewport?.height || 1400) *
													0.5000000000000002 -
													((componentViewport?.height || 1400) * 1) / 2) +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1wchqd9-container"}
									layoutDependency={layoutDependency}
									layoutId={"BMg9Y1bt_-container"}
									nodeId={"BMg9Y1bt_"}
									rendersWithMotion={true}
									scopeId={"uSzRf2WyT"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "BMg9Y1bt_",
										layoutId: "BMg9Y1bt_",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "hdexXEO_X",
										width: "100%",
										...addPropertyOverrides(
											{
												C_ZZDts2y: {
													variant: "QYQ1r9X7u",
												},
												GFIhwxsh9: {
													variant: "mWhcw8lXH",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-7G6fC.framer-e5g54u, .framer-7G6fC .framer-e5g54u { display: block; }",
	".framer-7G6fC.framer-1vlqip2 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: hidden; padding: 200px 100px 50px 100px; position: relative; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-7G6fC .framer-uzoqzu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 25px; height: min-content; justify-content: center; max-width: 1100px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-7G6fC .framer-10uv332 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-7G6fC .framer-1xv11j0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-7G6fC .framer-w9tee5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-7G6fC .framer-1gd1sx2 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-7G6fC .framer-11cgjwm { display: grid; flex: none; gap: 15px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-7G6fC .framer-yq5mik-container, .framer-7G6fC .framer-cuu991-container, .framer-7G6fC .framer-xbvzy9-container, .framer-7G6fC .framer-1rn7ipq-container, .framer-7G6fC .framer-17r2tkd-container, .framer-7G6fC .framer-1h3xmn-container { align-self: start; flex: none; height: auto; justify-self: start; position: relative; width: 100%; z-index: 1; }",
	".framer-7G6fC .framer-i4a7x7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 0; }",
	".framer-7G6fC .framer-1wchqd9-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: 0px; width: 100%; z-index: 0; }",
	".framer-7G6fC.framer-v-tvkrgq.framer-1vlqip2 { padding: 150px 40px 40px 40px; width: 810px; }",
	".framer-7G6fC.framer-v-tvkrgq .framer-1gd1sx2, .framer-7G6fC.framer-v-hh5j7x .framer-1gd1sx2 { max-width: 600px; }",
	".framer-7G6fC.framer-v-tvkrgq .framer-11cgjwm { grid-template-columns: repeat(2, minmax(50px, 1fr)); max-width: 810px; }",
	".framer-7G6fC.framer-v-hh5j7x.framer-1vlqip2 { padding: 80px 20px 40px 20px; width: 390px; will-change: unset; }",
	".framer-7G6fC.framer-v-hh5j7x .framer-10uv332 { gap: 0px; }",
	".framer-7G6fC.framer-v-hh5j7x .framer-1xv11j0 { gap: 20px; }",
	".framer-7G6fC.framer-v-hh5j7x .framer-w9tee5 { gap: 16px; }",
	".framer-7G6fC.framer-v-hh5j7x .framer-11cgjwm { gap: 10px; grid-template-columns: repeat(1, minmax(50px, 1fr)); max-width: 600px; }",
	...css,
];
var FrameruSzRf2WyT = withCSS(Component, css2, "framer-7G6fC");
var stdin_default3 = FrameruSzRf2WyT;
FrameruSzRf2WyT.displayName = "Benefit Section";
FrameruSzRf2WyT.defaultProps = {
	height: 722,
	width: 1200,
};
addPropertyControls(FrameruSzRf2WyT, {
	variant: {
		options: ["zISvybPEk", "C_ZZDts2y", "GFIhwxsh9"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameruSzRf2WyT,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...BenefitCardFonts,
		...GridFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:benefit-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GFIhwxsh9",
	md: "C_ZZDts2y",
	xl: "zISvybPEk",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6ea1ba37e05fac32a45356fef8456248177d20a6a62facacd4fc997df2f330fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders BenefitSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @memberof BenefitSectionFramerComponent
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6ea1ba37e05fac32a45356fef8456248177d20a6a62facacd4fc997df2f330fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var benefit_section_default = ComponentWithRoot;
export { benefit_section_default as default };
