// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6ea1ba37e05fac32 "Fumabase website, made from Aset", do not edit manually */
"use client";

import { stdin_default } from "./chunks/chunk-PHOGTW3T.js";
import "./chunks/chunk-SNH2M5FY.js";
import "./chunks/chunk-BTSBQWPZ.js";

// virtual:pricing-item
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "GH92NKo0U",
};
stdin_default.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={{
				augiA20Il: {
					path: "/",
				},
				k9spuiW9M: {
					path: "/404",
				},
			}}
			framerSiteId={
				"6ea1ba37e05fac32a45356fef8456248177d20a6a62facacd4fc997df2f330fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={{
				augiA20Il: {
					path: "/",
				},
				k9spuiW9M: {
					path: "/404",
				},
			}}
			framerSiteId={
				"6ea1ba37e05fac32a45356fef8456248177d20a6a62facacd4fc997df2f330fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
Object.assign(ComponentWithRoot, stdin_default);
export { ComponentWithRoot as default };
