// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 6ea1ba37e05fac32 "Fumabase website, made from Aset", do not edit manually */
"use client";

/**
 * @typedef Locale
 * A string that represents the locale.
 */

/**
 * @typedef Props
 * @property {React.ReactNode} [children] - The children components.
 * @property {Locale} [locale] - The active locale.
 * @property {React.CSSProperties} [style] - The component styles.
 * @property {string} [className] - Additional class names for the component.
 * @property {string} [id] - The component id.
 * @property {*} [width] - The component width.
 * @property {*} [height] - The component height.
 * @property {string} [layoutId] - The layout id.
 * @property {string} [name] - Name
 * @property {string} [subtitle] - Subtitle
 * @property {string} [content] - Content
 * @property {{src: string, srcSet?: string, alt?: string}} [image] - Image
 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { stdin_default } from "../chunks/chunk-2DA32EHW.js";
import "../chunks/chunk-UJNP7OPO.js";
import "../chunks/chunk-SNH2M5FY.js";
import { routes } from "../chunks/chunk-733MZEOY.js";

// virtual:card/testimonials-card
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6ea1ba37e05fac32a45356fef8456248177d20a6a62facacd4fc997df2f330fd"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders TestimonialsCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @memberof TestimonialsCardFramerComponent
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"6ea1ba37e05fac32a45356fef8456248177d20a6a62facacd4fc997df2f330fd"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonials_card_default = ComponentWithRoot;
export { testimonials_card_default as default };
