/**
 * Bundle chat CSS into a TypeScript module.
 *
 * Runs Tailwind CLI on chat.css (which contains both Tailwind directives and
 * hand-written styles), then scopes every selector under `.holocron-chat` so
 * the standalone ChatWidget can inject the styles into document.head without
 * leaking preflight/utilities into the host page. ChatHost imports the
 * resulting string constant.
 *
 * Why light DOM instead of shadow DOM: Chrome ignores `view-transition-name`
 * on elements inside shadow roots (only light-DOM elements are captured into
 * the document's view transition pseudo tree), so the pill → drawer morph
 * only works when the widget renders in the page's light DOM — same as the
 * docs-mode sidebar assistant.
 *
 * Scoping rules:
 * - `html` / `:host` selectors → `.holocron-chat` (the container element)
 * - selectors already containing `.holocron-chat` → kept as-is
 * - `::view-transition-*` pseudos → kept global (they live on the document root)
 * - `@keyframes`, `@property`, `@font-face` → kept global (name-scoped anyway)
 * - everything else (`*`, element selectors, utility classes) → prefixed with
 *   `.holocron-chat ` (descendant combinator). The uniform +1 class specificity
 *   bump keeps internal rule ordering intact.
 */

import { execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import postcss from 'postcss'

const root = path.resolve(import.meta.dirname, '..')
const chatDir = path.join(root, 'src/chat')

const input = path.join(chatDir, 'chat.css')
const compiled = path.join(chatDir, 'chat-compiled.css')
const output = path.join(chatDir, 'chat-css-bundle.ts')

const SCOPE = '.holocron-chat'

function scopeSelector(selector: string): string {
  const trimmed = selector.trim()
  // Document-scoped pseudos and rules that already reference the scope class
  if (trimmed.startsWith('::view-transition')) return trimmed
  if (trimmed.includes(SCOPE)) return trimmed
  // The container itself takes over the html/:host role (Tailwind preflight
  // emits `html, :host` selectors). Use :where() so these stay at zero
  // specificity and host-page overrides always win.
  if (trimmed === 'html') return `:where(${SCOPE})`
  if (trimmed.startsWith(':host')) {
    // :host → :where(.holocron-chat); :host(.dark) * → :where(.holocron-chat.dark) *
    return trimmed.replace(/^:host(?:\(([^)]*)\))?/, (_m, inner) => `:where(${SCOPE}${inner ?? ''})`)
  }
  // body/head rules can never apply inside the widget subtree — drop signal
  // is not worth the complexity; a dead descendant selector is harmless.
  return `${SCOPE} ${trimmed}`
}

function scopeCss(css: string): string {
  const ast = postcss.parse(css)
  ast.walkRules((rule) => {
    const parent = rule.parent
    if (parent?.type === 'atrule') {
      const name = (parent as postcss.AtRule).name
      if (name === 'keyframes' || name === 'property' || name === 'font-face') return
    }
    rule.selectors = rule.selectors.map(scopeSelector)
  })
  return ast.toString()
}

// Run Tailwind CLI: compiles chat.css (Tailwind directives + custom styles)
// into a flat CSS file with resolved utilities
console.log('Compiling chat.css with Tailwind CLI...')
execSync(`tailwindcss -i ${input} -o ${compiled}`, { cwd: root, stdio: 'inherit' })

const css = scopeCss(fs.readFileSync(compiled, 'utf-8'))

// Write TypeScript module with the CSS as a string constant
const ts = [
  '/**',
  ' * Auto-generated by scripts/bundle-chat-css.ts — do not edit manually.',
  ' * Compiled Tailwind utilities + chat styles, scoped under .holocron-chat.',
  ' * Injected into document.head by ChatHost (light DOM, so view transitions work).',
  ' */',
  '',
  '// prettier-ignore',
  'export const chatCssBundle = ' + JSON.stringify(css),
  '',
].join('\n')

fs.writeFileSync(output, ts)

// Clean up intermediate file
fs.unlinkSync(compiled)

console.log(`Wrote ${path.relative(root, output)} (${(css.length / 1024).toFixed(1)}KB)`)
