openapi: 3.1.3
info:
  title: Spiceflow Documentation
  description: Development documentation
  version: 0.0.0
paths:
  /api/openapi:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
components:
  schemas: {}
