openapi: 3.1.3
info:
  title: Spiceflow Documentation
  description: Development documentation
  version: 0.0.0
paths:
  /api/openapi:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
  /api/generateMessage:
    post:
      x-fern-streaming:
        format: sse
      parameters: []
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        default:
          description: ''
          content:
            '*/*':
              schema: {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messages:
                  type: array
                  items: {}
                siteId:
                  type: string
                chatId:
                  type: string
                branchId:
                  type: string
                githubFolder:
                  type: string
                currentSlug:
                  type: string
                filesInDraft:
                  type: object
                  propertyNames:
                    type: string
                  additionalProperties:
                    type: object
                    properties:
                      githubPath:
                        type: string
                      content:
                        default: ''
                        anyOf:
                          - type: string
                          - type: 'null'
                      addedLines:
                        type: number
                      deletedLines:
                        type: number
                    required:
                      - githubPath
                      - content
                todos:
                  type: array
                  items:
                    type: object
                    properties:
                      content:
                        description: Brief description of the task
                        type: string
                      status:
                        description: 'Current status of the task: pending, in_progress, completed, cancelled'
                        type: string
                        enum:
                          - pending
                          - in_progress
                          - completed
                          - cancelled
                      priority:
                        description: 'Priority level of the task: high, medium, low'
                        type: string
                        enum:
                          - high
                          - medium
                          - low
                      id:
                        description: Unique identifier for the todo item
                        type: string
                    required:
                      - content
                      - status
                      - priority
                      - id
              required:
                - messages
                - siteId
                - chatId
                - branchId
                - githubFolder
                - currentSlug
                - filesInDraft
components:
  schemas: {}
