// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project dfa04aa1c5bdec07 "Jet - SaaS Template (copy)", do not edit manually */
'use client'

import {
  AvoidLayoutJumping,
  stdin_default as stdin_default2,
} from './chunks/chunk-PZ2HPQWS.js'
import { className, css, fonts } from './chunks/chunk-ZDI2BEME.js'
import { TextGlitch } from './chunks/chunk-6NDTNB7L.js'
import { stdin_default } from './chunks/chunk-ALVRX4HO.js'
import './chunks/chunk-R527CHIA.js'

// virtual:accordion
import { Fragment as Fragment2 } from 'react'
import { ContextProviders } from 'unframer'

// /:https://framerusercontent.com/modules/5peN3Rk26PUb9JL0eGCW/2VeTL6qakTLsVoDF2Bh4/fCM_PzOxI.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime'
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer'
import { LayoutGroup, motion, MotionConfigContext } from 'unframer'
import * as React from 'react'
import { useRef } from 'react'
var LayoutJumpPreventerFonts = getFonts(AvoidLayoutJumping)
var IconFonts = getFonts(stdin_default2)
var TextGlitchFonts = getFonts(TextGlitch)
var MainSiteGridBorderFonts = getFonts(stdin_default)
var enabledGestures = {
  E3Hcex79n: {
    hover: true,
  },
}
var cycleOrder = ['NKMIZUkBe', 'E3Hcex79n']
var serializationHash = 'framer-NraYG'
var variantClassNames = {
  E3Hcex79n: 'framer-v-hxys06',
  NKMIZUkBe: 'framer-v-15hg7xp',
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  )
  return nextOverrides
}
var convertFromBoolean = (value, activeLocale) => {
  if (value) {
    return '0px 24px 0px 24px'
  } else {
    return '0px 24px 0px 34px'
  }
}
var numberToPixelString = (value) => {
  if (typeof value !== 'number') return value
  if (!Number.isFinite(value)) return void 0
  return Math.max(0, value) + 'px'
}
var transition1 = {
  bounce: 0,
  delay: 0,
  duration: 0.4,
  type: 'spring',
}
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  Closed: 'E3Hcex79n',
  Opened: 'NKMIZUkBe',
}
var getProps = ({
  answer,
  click,
  height,
  id,
  mobile,
  question,
  width,
  ...props
}) => {
  return {
    ...props,
    b0ibmrjZS:
      answer ??
      props.b0ibmrjZS ??
      'Not at all\u2014just enter your website URL and Jet handles the rest automatically.',
    RoXjuioKe: mobile ?? props.RoXjuioKe,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? 'NKMIZUkBe',
    vc2gg0XPn: question ?? props.vc2gg0XPn ?? 'Do I need coding skills?',
    Xf9o4NXyT: click ?? props.Xf9o4NXyT,
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    vc2gg0XPn,
    b0ibmrjZS,
    Xf9o4NXyT,
    RoXjuioKe,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'NKMIZUkBe',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)
  const onTap1o0uis2 = activeVariantCallback(async (...args) => {
    setGestureState({
      isPressed: false,
    })
    if (Xf9o4NXyT) {
      const res = await Xf9o4NXyT(...args)
      if (res === false) return false
    }
  })
  const sharedStyleClassNames = [className]
  const padding = numberToPixelString(
    convertFromBoolean(RoXjuioKe, activeLocale),
  )
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const isDisplayed = () => {
    if (gestureVariant === 'E3Hcex79n-hover') return false
    if (baseVariant === 'E3Hcex79n') return false
    return true
  }
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              'framer-15hg7xp',
              className2,
              classNames,
            )}
            data-framer-name={'Opened'}
            data-highlight={true}
            layoutDependency={layoutDependency}
            layoutId={'NKMIZUkBe'}
            onTap={onTap1o0uis2}
            ref={refBinding}
            style={{
              '--10ocmuz': padding,
              backgroundColor:
                'var(--token-fa07d228-afbe-4fad-9a44-2fb0dadd2a5e, rgb(23, 23, 23))',
              ...style,
            }}
            variants={{
              'E3Hcex79n-hover': {
                backgroundColor:
                  'var(--token-11d9ea5f-97fd-4136-81df-b44c454e15b1, rgb(12, 12, 12))',
              },
              E3Hcex79n: {
                backgroundColor: 'rgba(12, 12, 12, 0)',
              },
            }}
            {...addPropertyOverrides(
              {
                'E3Hcex79n-hover': {
                  'data-framer-name': void 0,
                },
                E3Hcex79n: {
                  'data-framer-name': 'Closed',
                },
              },
              baseVariant,
              gestureVariant,
            )}
          >
            <ComponentViewportProvider>
              <SmartComponentScopedContainer
                className={'framer-1y4dm77-container'}
                isAuthoredByUser={true}
                isModuleExternal={true}
                layoutDependency={layoutDependency}
                layoutId={'x52nZZRUv-container'}
                nodeId={'x52nZZRUv'}
                rendersWithMotion={true}
                scopeId={'fCM_PzOxI'}
                transformTemplate={transformTemplate1}
              >
                <AvoidLayoutJumping
                  direction={'vertical'}
                  height={'100%'}
                  id={'x52nZZRUv'}
                  layoutId={'x52nZZRUv'}
                  width={'100%'}
                />
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
            <motion.div
              className={'framer-17m71tt'}
              data-framer-name={'Question'}
              layoutDependency={layoutDependency}
              layoutId={'w1a7cwba6'}
            >
              <RichText
                __fromCanvasComponent={true}
                className={'framer-1uml4n6'}
                fonts={['Inter']}
                layoutDependency={layoutDependency}
                layoutId={'gCKAC9FT7'}
                style={{
                  '--extracted-a0htzi':
                    'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline',
                }}
                text={vc2gg0XPn}
                verticalAlignment={'top'}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.h3
                    className={'framer-styles-preset-d4fts2'}
                    data-styles-preset={'bRzBDjLMv'}
                    style={{
                      '--framer-text-color':
                        'var(--extracted-a0htzi, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))',
                    }}
                  >
                    {'Do I need coding skills?'}
                  </motion.h3>
                </React.Fragment>
              </RichText>
              {_jsx(stdin_default2, {
                animated: true,
                className: 'framer-wfnotp',
                layoutDependency,
                layoutId: 'fwsqEq3MN',
                style: {
                  '--13bnw74':
                    'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))',
                  rotate: 45,
                },
                variants: {
                  E3Hcex79n: {
                    rotate: 0,
                  },
                },
              })}
            </motion.div>
            {isDisplayed() && (
              <motion.div
                className={'framer-1082k5j'}
                data-framer-name={'Asnwer'}
                layoutDependency={layoutDependency}
                layoutId={'ZAbnRZaLO'}
              >
                <ComponentViewportProvider>
                  <SmartComponentScopedContainer
                    className={'framer-7f8gt1-container'}
                    isAuthoredByUser={true}
                    isModuleExternal={true}
                    layoutDependency={layoutDependency}
                    layoutId={'ZzDwcmcWq-container'}
                    nodeId={'ZzDwcmcWq'}
                    rendersWithMotion={true}
                    scopeId={'fCM_PzOxI'}
                  >
                    <TextGlitch
                      color={
                        'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))'
                      }
                      duration={350}
                      font={{
                        fontFamily: '"Raveo Variable Variable", sans-serif',
                        fontSize: '16px',
                        fontStyle: 'normal',
                        fontWeight: 1e3,
                        letterSpacing: '0em',
                        lineHeight: '1.5em',
                      }}
                      glitch={true}
                      height={'100%'}
                      id={'ZzDwcmcWq'}
                      layoutId={'ZzDwcmcWq'}
                      scrambleChars={
                        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?'
                      }
                      scrambleColor={
                        'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))'
                      }
                      scramblePercent={10}
                      speed={60}
                      style={{
                        maxWidth: '100%',
                        width: '100%',
                      }}
                      text={b0ibmrjZS}
                      variable={{
                        optical: 14,
                        weight: 450,
                      }}
                      width={'100%'}
                    />
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </motion.div>
            )}
            <ComponentViewportProvider
              height={(componentViewport?.height || 142) - -1}
              width={componentViewport?.width || '100vw'}
              y={(componentViewport?.y || 0) + 0}
              {...addPropertyOverrides(
                {
                  E3Hcex79n: {
                    height: (componentViewport?.height || 82) - 1,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <SmartComponentScopedContainer
                className={'framer-5xpor0-container'}
                layoutDependency={layoutDependency}
                layoutId={'oT13MnH97-container'}
                nodeId={'oT13MnH97'}
                rendersWithMotion={true}
                scopeId={'fCM_PzOxI'}
              >
                {_jsx(stdin_default, {
                  height: '100%',
                  id: 'oT13MnH97',
                  layoutId: 'oT13MnH97',
                  style: {
                    height: '100%',
                    width: '100%',
                  },
                  variant: 'oSdwqWnmP',
                  width: '100%',
                })}
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css2 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-NraYG.framer-1bx943e, .framer-NraYG .framer-1bx943e { display: block; }',
  '.framer-NraYG.framer-15hg7xp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: var(--10ocmuz); position: relative; width: 600px; }',
  '.framer-NraYG .framer-1y4dm77-container { flex: none; height: auto; left: 51%; position: absolute; top: 0px; width: auto; z-index: 1; }',
  '.framer-NraYG .framer-17m71tt { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 28px 0px 12px 0px; position: relative; width: 100%; }',
  '.framer-NraYG .framer-1uml4n6 { -webkit-user-select: none; flex: 1 0 0px; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }',
  '.framer-NraYG .framer-wfnotp { flex: none; height: var(--framer-aspect-ratio-supported, 26px); position: relative; width: 26px; }',
  '.framer-NraYG .framer-1082k5j { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 44px 28px 0px; position: relative; width: 100%; }',
  '.framer-NraYG .framer-7f8gt1-container { -webkit-user-select: none; flex: none; height: auto; max-width: 440px; position: relative; user-select: none; width: 100%; }',
  '.framer-NraYG .framer-5xpor0-container { -webkit-user-select: none; bottom: -1px; flex: none; left: 0px; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; z-index: 2; }',
  '.framer-NraYG.framer-v-hxys06 .framer-17m71tt { padding: 28px 0px 28px 0px; }',
  '.framer-NraYG.framer-v-hxys06 .framer-5xpor0-container { bottom: 1px; }',
  ...css,
]
var FramerfCM_PzOxI = withCSS(Component, css2, 'framer-NraYG')
var stdin_default3 = FramerfCM_PzOxI
FramerfCM_PzOxI.displayName = 'Accordion'
FramerfCM_PzOxI.defaultProps = {
  height: 142,
  width: 600,
}
addPropertyControls(FramerfCM_PzOxI, {
  variant: {
    options: ['NKMIZUkBe', 'E3Hcex79n'],
    optionTitles: ['Opened', 'Closed'],
    title: 'Variant',
    type: ControlType.Enum,
  },
  vc2gg0XPn: {
    defaultValue: 'Do I need coding skills?',
    displayTextArea: false,
    title: 'Question',
    type: ControlType.String,
  },
  b0ibmrjZS: {
    defaultValue:
      'Not at all\u2014just enter your website URL and Jet handles the rest automatically.',
    displayTextArea: true,
    title: 'Answer',
    type: ControlType.String,
  },
  Xf9o4NXyT: {
    title: 'Click',
    type: ControlType.EventHandler,
  },
  RoXjuioKe: {
    defaultValue: false,
    title: 'Mobile',
    type: ControlType.Boolean,
  },
})
var variationAxes = [
  {
    defaultValue: 14,
    maxValue: 32,
    minValue: 14,
    name: 'Optical size',
    tag: 'opsz',
  },
  {
    defaultValue: 400,
    maxValue: 900,
    minValue: 100,
    name: 'Weight',
    tag: 'wght',
  },
]
addFonts(
  FramerfCM_PzOxI,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400',
        },
        {
          family: 'Raveo Variable',
          source: 'builtIn',
          style: 'normal',
          url: 'https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2',
          variationAxes,
          weight: '1000',
        },
      ],
    },
    ...LayoutJumpPreventerFonts,
    ...IconFonts,
    ...TextGlitchFonts,
    ...MainSiteGridBorderFonts,
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// virtual:accordion
import { WithFramerBreakpoints } from 'unframer'
import { jsx } from 'react/jsx-runtime'
var locales = []
var defaultResponsiveVariants = {
  base: 'E3Hcex79n',
}
stdin_default3.Responsive = ({ locale, ...rest }) => {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={
        'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default3}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={
        'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default3, {
        ...rest,
      })}
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default3)
export { ComponentWithRoot as default }
