/* This file was generated by Unframer, do not edit manually */
import * as React from 'react'

import { UnframerBreakpoint } from 'unframer'

type Locale = string
export interface Props {
  children?: React.ReactNode
  locale?: Locale
  style?: React.CSSProperties
  className?: string
  id?: string
  width?: any
  height?: any
  layoutId?: string
  variant?:
    | 'Radial'
    | 'Lines'
    | 'Dots'
    | 'Pulser'
    | 'Speed'
    | 'Dot Speed'
    | 'Connections Center'
    | 'Connections Bottom'
    | 'Lines No Mask'
}

const AnimatedBackgroundsFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & {
  base: Props['variant']
}

AnimatedBackgroundsFramerComponent.Responsive = (
  props: Omit<Props, 'variant'> & { variants?: VariantsMap },
) => any

export default AnimatedBackgroundsFramerComponent
