// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project dfa04aa1c5bdec07 "Jet - SaaS Template (copy)", do not edit manually */
'use client'

import { className as className3, css as css3, fonts as fonts3 } from './chunks/chunk-ZFAO5FBW.js'
import { stdin_default as stdin_default4 } from './chunks/chunk-4DXVMHPR.js'
import { className as className2, css as css2, fonts as fonts2 } from './chunks/chunk-ZDI2BEME.js'
import { stdin_default as stdin_default2 } from './chunks/chunk-J43OPFLQ.js'
import { className, css, fonts } from './chunks/chunk-JWNC3KJW.js'
import { stdin_default as stdin_default3 } from './chunks/chunk-ALVRX4HO.js'
import { stdin_default } from './chunks/chunk-LCDELW7M.js'
import './chunks/chunk-R527CHIA.js'

// virtual:career-benefits-animation
import { Fragment as Fragment3 } from 'react'
import { ContextProviders } from 'unframer'

// /:https://framerusercontent.com/modules/v1e3pbFKfSuQ3oWZmDiv/CLwhgA5f2Oeh1X3xzniM/lc63zz_o2.js
import { jsx as _jsx2, jsxs as _jsxs2, Fragment as _Fragment } from 'react/jsx-runtime'
import {
  addFonts as addFonts2,
  addPropertyControls as addPropertyControls2,
  ChildrenCanSuspend,
  ComponentViewportProvider as ComponentViewportProvider2,
  ControlType as ControlType2,
  cx as cx2,
  getFonts as getFonts2,
  PathVariablesContext,
  SmartComponentScopedContainer as SmartComponentScopedContainer2,
  useActiveVariantCallback as useActiveVariantCallback2,
  useComponentViewport as useComponentViewport2,
  useLocaleInfo as useLocaleInfo2,
  useOnVariantChange as useOnVariantChange2,
  useQueryData,
  useVariantState as useVariantState2,
  withCSS as withCSS2,
} from 'unframer'
import { LayoutGroup as LayoutGroup2, motion as motion2, MotionConfigContext as MotionConfigContext2 } from 'unframer'
import * as React2 from 'react'
import { useRef as useRef2 } from 'react'

// /:https://framerusercontent.com/modules/cJAYt8YYdW7dFraF8eqe/Hhr8tzIQNKhwsTl14RPL/rOYJ7YUHT.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime'
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Instance,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOnVariantChange,
  useVariantState,
  withCSS,
} from 'unframer'
import { LayoutGroup, motion, MotionConfigContext } from 'unframer'
import * as React from 'react'
import { useRef } from 'react'
var MainSiteGridBorderFonts = getFonts(stdin_default3)
var CardSelectorFonts = getFonts(stdin_default4)
var enabledGestures = {
  XlAWaQvIF: {
    hover: true,
  },
}
var cycleOrder = ['XlAWaQvIF', 'Y6Iel_pkN', 'uTNORsn9b', 'qkRUB7du7']
var serializationHash = 'framer-dYwuC'
var variantClassNames = {
  qkRUB7du7: 'framer-v-9ymnuw',
  uTNORsn9b: 'framer-v-lkx0g8',
  XlAWaQvIF: 'framer-v-11o5diy',
  Y6Iel_pkN: 'framer-v-fp3u1n',
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]))
  return nextOverrides
}
var transition1 = {
  bounce: 0,
  delay: 0,
  duration: 0.6,
  type: 'spring',
}
var transition2 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: 'spring',
}
var transition3 = {
  bounce: 0,
  delay: 0.15,
  duration: 0.6,
  type: 'spring',
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  'Small Highlight Back': 'qkRUB7du7',
  'Small Highlight': 'uTNORsn9b',
  Default: 'XlAWaQvIF',
  Small: 'Y6Iel_pkN',
}
var getProps = ({ desc, height, icon, id, title, width, ...props }) => {
  return {
    ...props,
    aRyVltuVG: title ?? props.aRyVltuVG ?? 'Health & wellness',
    CXbVwy3T6: icon ?? props.CXbVwy3T6 ?? stdin_default2,
    Hv8iIIwok: desc ?? props.Hv8iIIwok ?? 'Comprehensive health coverage and wellness support.',
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'XlAWaQvIF',
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className4,
    layoutId,
    variant,
    aRyVltuVG,
    Hv8iIIwok,
    CXbVwy3T6,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'XlAWaQvIF',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)
  const onAppear1drlns1 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('qkRUB7du7', true), 150)
  })
  const onAppearoj3hw4 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('Y6Iel_pkN', true), 150)
  })
  useOnVariantChange(baseVariant, {
    qkRUB7du7: onAppearoj3hw4,
    uTNORsn9b: onAppear1drlns1,
  })
  const sharedStyleClassNames = [className3, className2, className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const isDisplayed = () => {
    if (['Y6Iel_pkN', 'uTNORsn9b', 'qkRUB7du7'].includes(baseVariant)) return false
    return true
  }
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition
          value={transition1}
          {...addPropertyOverrides(
            {
              qkRUB7du7: {
                value: transition2,
              },
              uTNORsn9b: {
                value: transition2,
              },
              Y6Iel_pkN: {
                value: transition2,
              },
            },
            baseVariant,
            gestureVariant,
          )}
        >
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(scopingClassNames, 'framer-11o5diy', className4, classNames)}
            data-framer-name={'Default'}
            layoutDependency={layoutDependency}
            layoutId={'XlAWaQvIF'}
            ref={refBinding}
            style={{
              ...style,
            }}
            {...addPropertyOverrides(
              {
                'XlAWaQvIF-hover': {
                  'data-framer-name': void 0,
                },
                qkRUB7du7: {
                  'data-framer-name': 'Small Highlight Back',
                  'data-highlight': true,
                },
                uTNORsn9b: {
                  'data-framer-name': 'Small Highlight',
                  'data-highlight': true,
                },
                Y6Iel_pkN: {
                  'data-framer-name': 'Small',
                },
              },
              baseVariant,
              gestureVariant,
            )}
          >
            <ComponentViewportProvider
              height={(componentViewport?.height || 250) - 0}
              width={componentViewport?.width || '100vw'}
              y={(componentViewport?.y || 0) + 0}
              {...addPropertyOverrides(
                {
                  qkRUB7du7: {
                    height: (componentViewport?.height || 76) - 0,
                  },
                  uTNORsn9b: {
                    height: (componentViewport?.height || 76) - 0,
                  },
                  Y6Iel_pkN: {
                    height: (componentViewport?.height || 76) - 0,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <SmartComponentScopedContainer
                className={'framer-1a3q5e5-container'}
                layoutDependency={layoutDependency}
                layoutId={'VLjV9tRPa-container'}
                nodeId={'VLjV9tRPa'}
                rendersWithMotion={true}
                scopeId={'rOYJ7YUHT'}
              >
                {_jsx(stdin_default3, {
                  height: '100%',
                  id: 'VLjV9tRPa',
                  layoutId: 'VLjV9tRPa',
                  style: {
                    height: '100%',
                    width: '100%',
                  },
                  variant: 'yzIFdYlxZ',
                  width: '100%',
                })}
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
            <Instance
              animated={true}
              className={'framer-13w9nbv'}
              Component={CXbVwy3T6}
              layoutDependency={layoutDependency}
              layoutId={'XZ4jybpJN'}
              style={{
                '--1m6trwb': 0,
                '--21h8s6': 'var(--token-c463d17c-ba87-44e7-9633-8d211629f523, rgb(128, 128, 128))',
                '--pgex8v': 1.5,
              }}
              variants={{
                'XlAWaQvIF-hover': {
                  '--21h8s6': 'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                },
                uTNORsn9b: {
                  '--21h8s6': 'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))',
                },
              }}
            />
            <motion.div
              className={'framer-rddiuf'}
              data-framer-name={'Text'}
              layoutDependency={layoutDependency}
              layoutId={'x3_iXIjoy'}
            >
              <RichText
                __fromCanvasComponent={true}
                className={'framer-1241nfw'}
                fonts={['Inter', 'Inter-Bold']}
                layoutDependency={layoutDependency}
                layoutId={'Yg1TZ170q'}
                style={{
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline',
                }}
                text={aRyVltuVG}
                variants={{
                  qkRUB7du7: {
                    '--extracted-r6o4lv': 'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                  },
                  uTNORsn9b: {
                    '--extracted-r6o4lv': 'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                  },
                  Y6Iel_pkN: {
                    '--extracted-r6o4lv': 'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                  },
                }}
                verticalAlignment={'top'}
                withExternalLayout={true}
                {...addPropertyOverrides(
                  {
                    qkRUB7du7: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={'framer-styles-preset-d4fts2'}
                            data-styles-preset={'bRzBDjLMv'}
                            style={{
                              '--framer-text-alignment': 'left',
                              '--framer-text-color':
                                'var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))',
                            }}
                          >
                            <motion.strong>{'Health & wellness'}</motion.strong>
                          </motion.p>
                        </React.Fragment>
                      ),
                    },
                    uTNORsn9b: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={'framer-styles-preset-d4fts2'}
                            data-styles-preset={'bRzBDjLMv'}
                            style={{
                              '--framer-text-alignment': 'left',
                              '--framer-text-color':
                                'var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))',
                            }}
                          >
                            <motion.strong>{'Health & wellness'}</motion.strong>
                          </motion.p>
                        </React.Fragment>
                      ),
                    },
                    Y6Iel_pkN: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={'framer-styles-preset-d4fts2'}
                            data-styles-preset={'bRzBDjLMv'}
                            style={{
                              '--framer-text-alignment': 'left',
                              '--framer-text-color':
                                'var(--extracted-r6o4lv, var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)))',
                            }}
                          >
                            <motion.strong>{'Health & wellness'}</motion.strong>
                          </motion.p>
                        </React.Fragment>
                      ),
                    },
                  },
                  baseVariant,
                  gestureVariant,
                )}
              >
                <React.Fragment>
                  <motion.h3 className={'framer-styles-preset-1mvjsmq'} data-styles-preset={'ZgYnZ4Tr8'}>
                    <motion.strong>{'Health & wellness'}</motion.strong>
                  </motion.h3>
                </React.Fragment>
              </RichText>
              <Transition
                {...addPropertyOverrides(
                  {
                    'XlAWaQvIF-hover': {
                      value: transition3,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                )}
              >
                <RichText
                  __fromCanvasComponent={true}
                  className={'framer-17gb6i1'}
                  fonts={['Inter']}
                  layoutDependency={layoutDependency}
                  layoutId={'cwMyDLBeR'}
                  style={{
                    '--extracted-r6o4lv': 'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))',
                    '--framer-link-text-color': 'rgb(0, 153, 255)',
                    '--framer-link-text-decoration': 'underline',
                    opacity: 0,
                  }}
                  text={Hv8iIIwok}
                  variants={{
                    'XlAWaQvIF-hover': {
                      opacity: 1,
                    },
                  }}
                  verticalAlignment={'top'}
                  withExternalLayout={true}
                >
                  <React.Fragment>
                    <motion.p
                      className={'framer-styles-preset-c9mga6'}
                      data-styles-preset={'Xa6VJQy2p'}
                      style={{
                        '--framer-text-color':
                          'var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))',
                      }}
                    >
                      {'Comprehensive health coverage and wellness support.'}
                    </motion.p>
                  </React.Fragment>
                </RichText>
              </Transition>
            </motion.div>
            {isDisplayed() && (
              <Image
                background={{
                  alt: '',
                  backgroundSize: 0.4,
                  fit: 'tile',
                  loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 0),
                  pixelHeight: 100,
                  pixelWidth: 100,
                  positionX: 'left',
                  positionY: 'top',
                  src: 'https://framerusercontent.com/images/6M98hkyWnZpsoNujUIpm3iEsVGw.png',
                }}
                className={'framer-h8s99a'}
                data-framer-name={'Dot'}
                draggable={'false'}
                layoutDependency={layoutDependency}
                layoutId={'xVO2W_S5q'}
                style={{
                  mask: 'radial-gradient(99.38650306748468% 162% at 0% 100%, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.5) 0.4047015765765766%, rgba(0,0,0,0) 0.6879926801801802%) add',
                  opacity: 0.1,
                  WebkitMask:
                    'radial-gradient(99.38650306748468% 162% at 0% 100%, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.5) 0.4047015765765766%, rgba(0,0,0,0) 0.6879926801801802%) add',
                }}
                variants={{
                  'XlAWaQvIF-hover': {
                    mask: 'radial-gradient(99.38650306748468% 162% at 1% 100%, rgba(0, 0, 0, 0) 0%, rgb(0, 0, 0) 77%, rgba(0,0,0,0) 100%) add',
                    WebkitMask:
                      'radial-gradient(99.38650306748468% 162% at 1% 100%, rgba(0, 0, 0, 0) 0%, rgb(0, 0, 0) 77%, rgba(0,0,0,0) 100%) add',
                  },
                }}
              />
            )}
            {isDisplayed() && (
              <ComponentViewportProvider
                height={(componentViewport?.height || 250) - 0}
                width={componentViewport?.width || '100vw'}
                y={(componentViewport?.y || 0) + 0}
              >
                <SmartComponentScopedContainer
                  className={'framer-1k7l2xw-container'}
                  layoutDependency={layoutDependency}
                  layoutId={'LYCV_VMlo-container'}
                  nodeId={'LYCV_VMlo'}
                  rendersWithMotion={true}
                  scopeId={'rOYJ7YUHT'}
                >
                  {_jsx(stdin_default4, {
                    height: '100%',
                    id: 'LYCV_VMlo',
                    layoutId: 'LYCV_VMlo',
                    style: {
                      height: '100%',
                      width: '100%',
                    },
                    variant: 'jcOPzl09p',
                    width: '100%',
                    ...addPropertyOverrides(
                      {
                        'XlAWaQvIF-hover': {
                          variant: 'CCKwLQUhX',
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  })}
                </SmartComponentScopedContainer>
              </ComponentViewportProvider>
            )}
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css4 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-dYwuC.framer-1a0ouki, .framer-dYwuC .framer-1a0ouki { display: block; }',
  '.framer-dYwuC.framer-11o5diy { align-content: flex-start; align-items: flex-start; cursor: default; display: flex; flex-direction: column; flex-wrap: nowrap; height: 250px; justify-content: space-between; overflow: visible; padding: 34px 34px 0px 34px; position: relative; width: 390px; }',
  '.framer-dYwuC .framer-1a3q5e5-container { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; z-index: 2; }',
  '.framer-dYwuC .framer-13w9nbv { flex: none; height: var(--framer-aspect-ratio-supported, 40px); position: relative; width: 40px; }',
  '.framer-dYwuC .framer-rddiuf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 34px 0px; position: relative; width: 100%; z-index: 4; }',
  '.framer-dYwuC .framer-1241nfw { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-dYwuC .framer-17gb6i1 { bottom: -58px; flex: none; height: auto; left: 0px; max-width: 240px; position: absolute; white-space: pre-wrap; width: 240px; word-break: break-word; word-wrap: break-word; z-index: 1; }',
  '.framer-dYwuC .framer-h8s99a { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; overflow: hidden; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; z-index: 1; }',
  '.framer-dYwuC .framer-1k7l2xw-container { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; z-index: 4; }',
  '.framer-dYwuC.framer-v-fp3u1n.framer-11o5diy { align-content: center; align-items: center; flex-direction: row; gap: 12px; height: min-content; justify-content: flex-start; padding: 24px; }',
  '.framer-dYwuC.framer-v-fp3u1n .framer-13w9nbv, .framer-dYwuC.framer-v-lkx0g8 .framer-13w9nbv, .framer-dYwuC.framer-v-9ymnuw .framer-13w9nbv { height: var(--framer-aspect-ratio-supported, 28px); width: 28px; }',
  '.framer-dYwuC.framer-v-fp3u1n .framer-rddiuf, .framer-dYwuC.framer-v-lkx0g8 .framer-rddiuf, .framer-dYwuC.framer-v-9ymnuw .framer-rddiuf { flex: 1 0 0px; padding: 0px; width: 1px; }',
  '.framer-dYwuC.framer-v-lkx0g8.framer-11o5diy { align-content: center; align-items: center; flex-direction: row; gap: 12px; height: min-content; justify-content: flex-start; padding: 24px 24px 24px 32px; width: 390px; }',
  '.framer-dYwuC.framer-v-9ymnuw.framer-11o5diy { align-content: center; align-items: center; flex-direction: row; gap: 12px; height: min-content; justify-content: flex-start; padding: 24px; width: 390px; }',
  '.framer-dYwuC.framer-v-11o5diy.hover .framer-17gb6i1 { bottom: unset; left: unset; position: relative; }',
  ...css3,
  ...css2,
  ...css,
]
var FramerrOYJ7YUHT = withCSS(Component, css4, 'framer-dYwuC')
var stdin_default5 = FramerrOYJ7YUHT
FramerrOYJ7YUHT.displayName = 'Career Benefit Card'
FramerrOYJ7YUHT.defaultProps = {
  height: 250,
  width: 390,
}
addPropertyControls(FramerrOYJ7YUHT, {
  variant: {
    options: ['XlAWaQvIF', 'Y6Iel_pkN', 'uTNORsn9b', 'qkRUB7du7'],
    optionTitles: ['Default', 'Small', 'Small Highlight', 'Small Highlight Back'],
    title: 'Variant',
    type: ControlType.Enum,
  },
  aRyVltuVG: {
    defaultValue: 'Health & wellness',
    displayTextArea: false,
    title: 'Title',
    type: ControlType.String,
  },
  Hv8iIIwok: {
    defaultValue: 'Comprehensive health coverage and wellness support.',
    displayTextArea: false,
    title: 'Desc',
    type: ControlType.String,
  },
  CXbVwy3T6: {
    defaultValue: {
      identifier: 'module:BLjRczXRCa2XMZlRX1af/3JLV0naPYn0LHwD9pOLX/ljGcHeWyh.js:default',
      moduleId: 'BLjRczXRCa2XMZlRX1af',
    },
    setModuleId: 'omX0gWFPqDwhaiWwf6ab',
    title: 'Icon',
    type: ControlType.VectorSetItem,
  },
})
addFonts(
  FramerrOYJ7YUHT,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2',
          weight: '700',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2',
          weight: '700',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2',
          weight: '700',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2',
          weight: '700',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2',
          weight: '700',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2',
          weight: '700',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2',
          weight: '700',
        },
      ],
    },
    ...MainSiteGridBorderFonts,
    ...CardSelectorFonts,
    ...getFontsFromSharedStyle(fonts3),
    ...getFontsFromSharedStyle(fonts2),
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// /:https://framerusercontent.com/modules/v1e3pbFKfSuQ3oWZmDiv/CLwhgA5f2Oeh1X3xzniM/lc63zz_o2.js
var CareerBenefitCardFonts = getFonts2(stdin_default5)
var cycleOrder2 = ['xR7FXAEZA', 'MqzCAq7xq', 'N8LAzaIAl', 'DiJ08a1r6', 'EH3qdrbt6', 'AQWKE9gxI', 'zqb6rOHn3']
var serializationHash2 = 'framer-4rGRL'
var variantClassNames2 = {
  AQWKE9gxI: 'framer-v-124watk',
  DiJ08a1r6: 'framer-v-1u78ud9',
  EH3qdrbt6: 'framer-v-1mbu383',
  MqzCAq7xq: 'framer-v-1kxax33',
  N8LAzaIAl: 'framer-v-qgtk1l',
  xR7FXAEZA: 'framer-v-rs9ixs',
  zqb6rOHn3: 'framer-v-16o2osr',
}
function addPropertyOverrides2(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]))
  return nextOverrides
}
var transition12 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: 'spring',
}
var QueryData = ({ query: query2, pageSize, children }) => {
  const data = useQueryData(query2)
  return children(data)
}
var Transition2 = ({ value, children }) => {
  const config = React2.useContext(MotionConfigContext2)
  const transition = value ?? config.transition
  const contextValue = React2.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return <MotionConfigContext2.Provider value={contextValue}>{children}</MotionConfigContext2.Provider>
}
var Variants2 = motion2.create(React2.Fragment)
var humanReadableVariantMap2 = {
  'Cycle (1)': 'MqzCAq7xq',
  'Cycle (2)': 'N8LAzaIAl',
  'Cycle (3)': 'DiJ08a1r6',
  'Cycle (4)': 'EH3qdrbt6',
  'Cycle (5)': 'AQWKE9gxI',
  'Cycle (6)': 'zqb6rOHn3',
  Default: 'xR7FXAEZA',
}
var getProps2 = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant: humanReadableVariantMap2[props.variant] ?? props.variant ?? 'xR7FXAEZA',
  }
}
var createLayoutDependency2 = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
  const fallbackRef = useRef2(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React2.useId()
  const { activeLocale, setLocale } = useLocaleInfo2()
  const componentViewport = useComponentViewport2()
  const {
    style,
    className: className4,
    layoutId,
    variant,
    PGtnvEERdfQL_u5B83,
    szPqLt0TtfQL_u5B83,
    h19S7BCx9fQL_u5B83,
    tu9YX4fNGfQL_u5B83,
    eTLfGfFHBfQL_u5B83,
    u0g3twFNdfQL_u5B83,
    W3F6rWNmmfQL_u5B83,
    ZmxxV4fTMfQL_u5B83,
    jQHMZjkTnfQL_u5B83,
    ZzJICKY8QfQL_u5B83,
    e8wCD5VDifQL_u5B83,
    YDwhjuhzZfQL_u5B83,
    I1zL4okM5fQL_u5B83,
    GsmhfEULXfQL_u5B83,
    lG_KoCbSFfQL_u5B83,
    gPhkPBSRFfQL_u5B83,
    weQHD0OCkfQL_u5B83,
    LEoaXmHFmfQL_u5B83,
    k2CHhHMepfQL_u5B83,
    idfQL_u5B83,
    ...restProps
  } = getProps2(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState2({
    cycleOrder: cycleOrder2,
    defaultVariant: 'xR7FXAEZA',
    ref: refBinding,
    variant,
    variantClassNames: variantClassNames2,
  })
  const layoutDependency = createLayoutDependency2(props, variants)
  const { activeVariantCallback, delay } = useActiveVariantCallback2(baseVariant)
  const onAppeartanfm6 = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('MqzCAq7xq', true), 2e3)
  })
  const onAppeartw942f = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('N8LAzaIAl', true), 50)
  })
  const onAppear1dba98m = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('DiJ08a1r6', true), 100)
  })
  const onAppearfztnl = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('EH3qdrbt6', true), 150)
  })
  const onAppearzlm76e = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('AQWKE9gxI', true), 200)
  })
  const onAppearxre07b = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('zqb6rOHn3', true), 250)
  })
  const onAppear407tgm = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('xR7FXAEZA', true), 300)
  })
  useOnVariantChange2(baseVariant, {
    AQWKE9gxI: onAppearxre07b,
    default: onAppeartanfm6,
    DiJ08a1r6: onAppearfztnl,
    EH3qdrbt6: onAppearzlm76e,
    MqzCAq7xq: onAppeartw942f,
    N8LAzaIAl: onAppear1dba98m,
    zqb6rOHn3: onAppear407tgm,
  })
  const sharedStyleClassNames = []
  const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames)
  return (
    <LayoutGroup2 id={layoutId ?? defaultLayoutId}>
      <Variants2 animate={variants} initial={false}>
        <Transition2 value={transition12}>
          <motion2.div
            {...restProps}
            {...gestureHandlers}
            className={cx2(scopingClassNames, 'framer-rs9ixs', className4, classNames)}
            data-framer-name={'Default'}
            data-highlight={true}
            layoutDependency={layoutDependency}
            layoutId={'xR7FXAEZA'}
            ref={refBinding}
            style={{
              ...style,
            }}
            {...addPropertyOverrides2(
              {
                AQWKE9gxI: {
                  'data-framer-name': 'Cycle (5)',
                },
                DiJ08a1r6: {
                  'data-framer-name': 'Cycle (3)',
                },
                EH3qdrbt6: {
                  'data-framer-name': 'Cycle (4)',
                },
                MqzCAq7xq: {
                  'data-framer-name': 'Cycle (1)',
                },
                N8LAzaIAl: {
                  'data-framer-name': 'Cycle (2)',
                },
                zqb6rOHn3: {
                  'data-framer-name': 'Cycle (6)',
                },
              },
              baseVariant,
              gestureVariant,
            )}
          >
            <motion2.div
              className={'framer-h0wk55'}
              data-framer-name={'Customization Frame'}
              layoutDependency={layoutDependency}
              layoutId={'fQL_u5B83'}
            >
              <ChildrenCanSuspend>
                <QueryData
                  query={{
                    from: {
                      alias: 'fQL_u5B83',
                      data: stdin_default,
                      type: 'Collection',
                    },
                    limit: {
                      type: 'LiteralValue',
                      value: 1,
                    },
                    select: [
                      {
                        collection: 'fQL_u5B83',
                        name: 'PGtnvEERd',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'szPqLt0Tt',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'h19S7BCx9',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'tu9YX4fNG',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'eTLfGfFHB',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'u0g3twFNd',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'W3F6rWNmm',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'ZmxxV4fTM',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'jQHMZjkTn',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'ZzJICKY8Q',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'e8wCD5VDi',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'YDwhjuhzZ',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'I1zL4okM5',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'GsmhfEULX',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'lG_KoCbSF',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'gPhkPBSRF',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'weQHD0OCk',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'LEoaXmHFm',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'k2CHhHMep',
                        type: 'Identifier',
                      },
                      {
                        collection: 'fQL_u5B83',
                        name: 'id',
                        type: 'Identifier',
                      },
                    ],
                  }}
                >
                  {(collection, paginationInfo, loadMore) => (
                    <_Fragment>
                      {collection?.map(
                        (
                          {
                            e8wCD5VDi: e8wCD5VDifQL_u5B832,
                            eTLfGfFHB: eTLfGfFHBfQL_u5B832,
                            gPhkPBSRF: gPhkPBSRFfQL_u5B832,
                            GsmhfEULX: GsmhfEULXfQL_u5B832,
                            h19S7BCx9: h19S7BCx9fQL_u5B832,
                            I1zL4okM5: I1zL4okM5fQL_u5B832,
                            id: idfQL_u5B832,
                            jQHMZjkTn: jQHMZjkTnfQL_u5B832,
                            k2CHhHMep: k2CHhHMepfQL_u5B832,
                            LEoaXmHFm: LEoaXmHFmfQL_u5B832,
                            lG_KoCbSF: lG_KoCbSFfQL_u5B832,
                            PGtnvEERd: PGtnvEERdfQL_u5B832,
                            szPqLt0Tt: szPqLt0TtfQL_u5B832,
                            tu9YX4fNG: tu9YX4fNGfQL_u5B832,
                            u0g3twFNd: u0g3twFNdfQL_u5B832,
                            W3F6rWNmm: W3F6rWNmmfQL_u5B832,
                            weQHD0OCk: weQHD0OCkfQL_u5B832,
                            YDwhjuhzZ: YDwhjuhzZfQL_u5B832,
                            ZmxxV4fTM: ZmxxV4fTMfQL_u5B832,
                            ZzJICKY8Q: ZzJICKY8QfQL_u5B832,
                          },
                          index,
                        ) => {
                          PGtnvEERdfQL_u5B832 ??= ''
                          szPqLt0TtfQL_u5B832 ??= ''
                          tu9YX4fNGfQL_u5B832 ??= ''
                          eTLfGfFHBfQL_u5B832 ??= ''
                          W3F6rWNmmfQL_u5B832 ??= ''
                          ZmxxV4fTMfQL_u5B832 ??= ''
                          ZzJICKY8QfQL_u5B832 ??= ''
                          e8wCD5VDifQL_u5B832 ??= ''
                          I1zL4okM5fQL_u5B832 ??= ''
                          GsmhfEULXfQL_u5B832 ??= ''
                          gPhkPBSRFfQL_u5B832 ??= ''
                          weQHD0OCkfQL_u5B832 ??= ''
                          k2CHhHMepfQL_u5B832 ??= ''
                          return (
                            <LayoutGroup2 id={`fQL_u5B83-${idfQL_u5B832}`}>
                              <PathVariablesContext.Provider
                                value={{
                                  k2CHhHMep: k2CHhHMepfQL_u5B832,
                                }}
                              >
                                <motion2.div
                                  className={'framer-1ily7th'}
                                  data-framer-name={'Content'}
                                  layoutDependency={layoutDependency}
                                  layoutId={'zLL179nwG'}
                                >
                                  <ComponentViewportProvider2
                                    height={
                                      Math.max(
                                        0,
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 -
                                          0 -
                                          0) /
                                          6,
                                      ) * 1
                                    }
                                    width={componentViewport?.width || '100vw'}
                                    y={
                                      (componentViewport?.y || 0) +
                                      0 +
                                      (((componentViewport?.height || 580) -
                                        0 -
                                        (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 + 0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      ((Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                        0 -
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 +
                                          0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      0
                                    }
                                  >
                                    <SmartComponentScopedContainer2
                                      className={'framer-1r3stce-container'}
                                      layoutDependency={layoutDependency}
                                      layoutId={'QlfnIFJnH-container'}
                                      nodeId={'QlfnIFJnH'}
                                      rendersWithMotion={true}
                                      scopeId={'lc63zz_o2'}
                                    >
                                      {_jsx2(stdin_default5, {
                                        aRyVltuVG: PGtnvEERdfQL_u5B832,
                                        CXbVwy3T6: h19S7BCx9fQL_u5B832,
                                        height: '100%',
                                        Hv8iIIwok: szPqLt0TtfQL_u5B832,
                                        id: 'QlfnIFJnH',
                                        layoutId: 'QlfnIFJnH',
                                        style: {
                                          height: '100%',
                                          width: '100%',
                                        },
                                        variant: 'Y6Iel_pkN',
                                        width: '100%',
                                        ...addPropertyOverrides2(
                                          {
                                            AQWKE9gxI: {
                                              variant: 'uTNORsn9b',
                                            },
                                            DiJ08a1r6: {
                                              variant: 'uTNORsn9b',
                                            },
                                            EH3qdrbt6: {
                                              variant: 'uTNORsn9b',
                                            },
                                            MqzCAq7xq: {
                                              variant: 'uTNORsn9b',
                                            },
                                            N8LAzaIAl: {
                                              variant: 'uTNORsn9b',
                                            },
                                            zqb6rOHn3: {
                                              variant: 'uTNORsn9b',
                                            },
                                          },
                                          baseVariant,
                                          gestureVariant,
                                        ),
                                      })}
                                    </SmartComponentScopedContainer2>
                                  </ComponentViewportProvider2>
                                  <ComponentViewportProvider2
                                    height={
                                      Math.max(
                                        0,
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 -
                                          0 -
                                          0) /
                                          6,
                                      ) * 1
                                    }
                                    width={componentViewport?.width || '100vw'}
                                    y={
                                      (componentViewport?.y || 0) +
                                      0 +
                                      (((componentViewport?.height || 580) -
                                        0 -
                                        (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 + 0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      ((Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                        0 -
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 +
                                          0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      (0 +
                                        Math.max(
                                          0,
                                          (Math.max(
                                            0,
                                            (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                              0 -
                                              0) /
                                              1,
                                          ) *
                                            1 -
                                            0 -
                                            0) /
                                            6,
                                        ) *
                                          1 +
                                        0)
                                    }
                                  >
                                    <SmartComponentScopedContainer2
                                      className={'framer-18wjkff-container'}
                                      layoutDependency={layoutDependency}
                                      layoutId={'u6wceNG9f-container'}
                                      nodeId={'u6wceNG9f'}
                                      rendersWithMotion={true}
                                      scopeId={'lc63zz_o2'}
                                    >
                                      {_jsx2(stdin_default5, {
                                        aRyVltuVG: tu9YX4fNGfQL_u5B832,
                                        CXbVwy3T6: u0g3twFNdfQL_u5B832,
                                        height: '100%',
                                        Hv8iIIwok: eTLfGfFHBfQL_u5B832,
                                        id: 'u6wceNG9f',
                                        layoutId: 'u6wceNG9f',
                                        style: {
                                          height: '100%',
                                          width: '100%',
                                        },
                                        variant: 'Y6Iel_pkN',
                                        width: '100%',
                                        ...addPropertyOverrides2(
                                          {
                                            AQWKE9gxI: {
                                              variant: 'uTNORsn9b',
                                            },
                                            DiJ08a1r6: {
                                              variant: 'uTNORsn9b',
                                            },
                                            EH3qdrbt6: {
                                              variant: 'uTNORsn9b',
                                            },
                                            N8LAzaIAl: {
                                              variant: 'uTNORsn9b',
                                            },
                                            zqb6rOHn3: {
                                              variant: 'uTNORsn9b',
                                            },
                                          },
                                          baseVariant,
                                          gestureVariant,
                                        ),
                                      })}
                                    </SmartComponentScopedContainer2>
                                  </ComponentViewportProvider2>
                                  <ComponentViewportProvider2
                                    height={
                                      Math.max(
                                        0,
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 -
                                          0 -
                                          0) /
                                          6,
                                      ) * 1
                                    }
                                    width={componentViewport?.width || '100vw'}
                                    y={
                                      (componentViewport?.y || 0) +
                                      0 +
                                      (((componentViewport?.height || 580) -
                                        0 -
                                        (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 + 0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      ((Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                        0 -
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 +
                                          0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      (0 +
                                        (Math.max(
                                          0,
                                          (Math.max(
                                            0,
                                            (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                              0 -
                                              0) /
                                              1,
                                          ) *
                                            1 -
                                            0 -
                                            0) /
                                            6,
                                        ) *
                                          1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1) +
                                        0)
                                    }
                                  >
                                    <SmartComponentScopedContainer2
                                      className={'framer-1fbq0mh-container'}
                                      layoutDependency={layoutDependency}
                                      layoutId={'wTNOt40L0-container'}
                                      nodeId={'wTNOt40L0'}
                                      rendersWithMotion={true}
                                      scopeId={'lc63zz_o2'}
                                    >
                                      {_jsx2(stdin_default5, {
                                        aRyVltuVG: W3F6rWNmmfQL_u5B832,
                                        CXbVwy3T6: jQHMZjkTnfQL_u5B832,
                                        height: '100%',
                                        Hv8iIIwok: ZmxxV4fTMfQL_u5B832,
                                        id: 'wTNOt40L0',
                                        layoutId: 'wTNOt40L0',
                                        style: {
                                          height: '100%',
                                          width: '100%',
                                        },
                                        variant: 'Y6Iel_pkN',
                                        width: '100%',
                                        ...addPropertyOverrides2(
                                          {
                                            AQWKE9gxI: {
                                              variant: 'uTNORsn9b',
                                            },
                                            DiJ08a1r6: {
                                              variant: 'uTNORsn9b',
                                            },
                                            EH3qdrbt6: {
                                              variant: 'uTNORsn9b',
                                            },
                                            zqb6rOHn3: {
                                              variant: 'uTNORsn9b',
                                            },
                                          },
                                          baseVariant,
                                          gestureVariant,
                                        ),
                                      })}
                                    </SmartComponentScopedContainer2>
                                  </ComponentViewportProvider2>
                                  <ComponentViewportProvider2
                                    height={
                                      Math.max(
                                        0,
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 -
                                          0 -
                                          0) /
                                          6,
                                      ) * 1
                                    }
                                    width={componentViewport?.width || '100vw'}
                                    y={
                                      (componentViewport?.y || 0) +
                                      0 +
                                      (((componentViewport?.height || 580) -
                                        0 -
                                        (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 + 0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      ((Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                        0 -
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 +
                                          0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      (0 +
                                        (Math.max(
                                          0,
                                          (Math.max(
                                            0,
                                            (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                              0 -
                                              0) /
                                              1,
                                          ) *
                                            1 -
                                            0 -
                                            0) /
                                            6,
                                        ) *
                                          1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1) +
                                        0)
                                    }
                                  >
                                    <SmartComponentScopedContainer2
                                      className={'framer-iyusjy-container'}
                                      layoutDependency={layoutDependency}
                                      layoutId={'wj7NfAwOa-container'}
                                      nodeId={'wj7NfAwOa'}
                                      rendersWithMotion={true}
                                      scopeId={'lc63zz_o2'}
                                    >
                                      {_jsx2(stdin_default5, {
                                        aRyVltuVG: ZzJICKY8QfQL_u5B832,
                                        CXbVwy3T6: YDwhjuhzZfQL_u5B832,
                                        height: '100%',
                                        Hv8iIIwok: e8wCD5VDifQL_u5B832,
                                        id: 'wj7NfAwOa',
                                        layoutId: 'wj7NfAwOa',
                                        style: {
                                          height: '100%',
                                          width: '100%',
                                        },
                                        variant: 'Y6Iel_pkN',
                                        width: '100%',
                                        ...addPropertyOverrides2(
                                          {
                                            AQWKE9gxI: {
                                              variant: 'uTNORsn9b',
                                            },
                                            EH3qdrbt6: {
                                              variant: 'uTNORsn9b',
                                            },
                                            zqb6rOHn3: {
                                              variant: 'uTNORsn9b',
                                            },
                                          },
                                          baseVariant,
                                          gestureVariant,
                                        ),
                                      })}
                                    </SmartComponentScopedContainer2>
                                  </ComponentViewportProvider2>
                                  <ComponentViewportProvider2
                                    height={
                                      Math.max(
                                        0,
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 -
                                          0 -
                                          0) /
                                          6,
                                      ) * 1
                                    }
                                    width={componentViewport?.width || '100vw'}
                                    y={
                                      (componentViewport?.y || 0) +
                                      0 +
                                      (((componentViewport?.height || 580) -
                                        0 -
                                        (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 + 0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      ((Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                        0 -
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 +
                                          0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      (0 +
                                        (Math.max(
                                          0,
                                          (Math.max(
                                            0,
                                            (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                              0 -
                                              0) /
                                              1,
                                          ) *
                                            1 -
                                            0 -
                                            0) /
                                            6,
                                        ) *
                                          1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1) +
                                        0)
                                    }
                                  >
                                    <SmartComponentScopedContainer2
                                      className={'framer-q219oo-container'}
                                      layoutDependency={layoutDependency}
                                      layoutId={'jNpNAhkmi-container'}
                                      nodeId={'jNpNAhkmi'}
                                      rendersWithMotion={true}
                                      scopeId={'lc63zz_o2'}
                                    >
                                      {_jsx2(stdin_default5, {
                                        aRyVltuVG: I1zL4okM5fQL_u5B832,
                                        CXbVwy3T6: lG_KoCbSFfQL_u5B832,
                                        height: '100%',
                                        Hv8iIIwok: GsmhfEULXfQL_u5B832,
                                        id: 'jNpNAhkmi',
                                        layoutId: 'jNpNAhkmi',
                                        style: {
                                          height: '100%',
                                          width: '100%',
                                        },
                                        variant: 'Y6Iel_pkN',
                                        width: '100%',
                                        ...addPropertyOverrides2(
                                          {
                                            AQWKE9gxI: {
                                              variant: 'uTNORsn9b',
                                            },
                                            zqb6rOHn3: {
                                              variant: 'uTNORsn9b',
                                            },
                                          },
                                          baseVariant,
                                          gestureVariant,
                                        ),
                                      })}
                                    </SmartComponentScopedContainer2>
                                  </ComponentViewportProvider2>
                                  <ComponentViewportProvider2
                                    height={
                                      Math.max(
                                        0,
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 -
                                          0 -
                                          0) /
                                          6,
                                      ) * 1
                                    }
                                    width={componentViewport?.width || '100vw'}
                                    y={
                                      (componentViewport?.y || 0) +
                                      0 +
                                      (((componentViewport?.height || 580) -
                                        0 -
                                        (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 + 0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      ((Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                        0 -
                                        (Math.max(
                                          0,
                                          (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 - 0 - 0) /
                                            1,
                                        ) *
                                          1 +
                                          0)) /
                                        2 +
                                        0 +
                                        0) +
                                      0 +
                                      (0 +
                                        (Math.max(
                                          0,
                                          (Math.max(
                                            0,
                                            (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                              0 -
                                              0) /
                                              1,
                                          ) *
                                            1 -
                                            0 -
                                            0) /
                                            6,
                                        ) *
                                          1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1 +
                                          Math.max(
                                            0,
                                            (Math.max(
                                              0,
                                              (Math.max(0, ((componentViewport?.height || 580) - 0 - 0) / 1) * 1 -
                                                0 -
                                                0) /
                                                1,
                                            ) *
                                              1 -
                                              0 -
                                              0) /
                                              6,
                                          ) *
                                            1) +
                                        0)
                                    }
                                  >
                                    <SmartComponentScopedContainer2
                                      className={'framer-pzgada-container'}
                                      layoutDependency={layoutDependency}
                                      layoutId={'roQtyXuTI-container'}
                                      nodeId={'roQtyXuTI'}
                                      rendersWithMotion={true}
                                      scopeId={'lc63zz_o2'}
                                    >
                                      {_jsx2(stdin_default5, {
                                        aRyVltuVG: gPhkPBSRFfQL_u5B832,
                                        CXbVwy3T6: LEoaXmHFmfQL_u5B832,
                                        height: '100%',
                                        Hv8iIIwok: weQHD0OCkfQL_u5B832,
                                        id: 'roQtyXuTI',
                                        layoutId: 'roQtyXuTI',
                                        style: {
                                          height: '100%',
                                          width: '100%',
                                        },
                                        variant: 'Y6Iel_pkN',
                                        width: '100%',
                                        ...addPropertyOverrides2(
                                          {
                                            zqb6rOHn3: {
                                              variant: 'uTNORsn9b',
                                            },
                                          },
                                          baseVariant,
                                          gestureVariant,
                                        ),
                                      })}
                                    </SmartComponentScopedContainer2>
                                  </ComponentViewportProvider2>
                                </motion2.div>
                              </PathVariablesContext.Provider>
                            </LayoutGroup2>
                          )
                        },
                      )}
                    </_Fragment>
                  )}
                </QueryData>
              </ChildrenCanSuspend>
            </motion2.div>
          </motion2.div>
        </Transition2>
      </Variants2>
    </LayoutGroup2>
  )
})
var css5 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-4rGRL.framer-dhn1t1, .framer-4rGRL .framer-dhn1t1 { display: block; }',
  '.framer-4rGRL.framer-rs9ixs { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 580px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 303px; }',
  '.framer-4rGRL .framer-h0wk55 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 1px; justify-content: center; padding: 0px; position: relative; width: 100%; }',
  '.framer-4rGRL .framer-1ily7th { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 1px; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }',
  '.framer-4rGRL .framer-1r3stce-container, .framer-4rGRL .framer-18wjkff-container, .framer-4rGRL .framer-1fbq0mh-container, .framer-4rGRL .framer-iyusjy-container, .framer-4rGRL .framer-q219oo-container, .framer-4rGRL .framer-pzgada-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; z-index: 3; }',
]
var Framerlc63zz_o2 = withCSS2(Component2, css5, 'framer-4rGRL')
var stdin_default6 = Framerlc63zz_o2
Framerlc63zz_o2.displayName = 'Career Benefits Animation'
Framerlc63zz_o2.defaultProps = {
  height: 580,
  width: 303,
}
addPropertyControls2(Framerlc63zz_o2, {
  variant: {
    options: ['xR7FXAEZA', 'MqzCAq7xq', 'N8LAzaIAl', 'DiJ08a1r6', 'EH3qdrbt6', 'AQWKE9gxI', 'zqb6rOHn3'],
    optionTitles: ['Default', 'Cycle (1)', 'Cycle (2)', 'Cycle (3)', 'Cycle (4)', 'Cycle (5)', 'Cycle (6)'],
    title: 'Variant',
    type: ControlType2.Enum,
  },
})
addFonts2(
  Framerlc63zz_o2,
  [
    {
      explicitInter: true,
      fonts: [],
    },
    ...CareerBenefitCardFonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// virtual:career-benefits-animation
import { WithFramerBreakpoints } from 'unframer'
import { jsx } from 'react/jsx-runtime'
var locales = []
var defaultResponsiveVariants = {
  base: 'xR7FXAEZA',
}
stdin_default6.Responsive = ({ locale, ...rest }) => {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints Component={stdin_default6} variants={defaultResponsiveVariants} {...rest} />
    </ContextProviders>
  )
}
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default6, {
        ...rest,
      })}
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default6)
export { ComponentWithRoot as default }
