/* This file was generated by Unframer, do not edit manually */
import * as React from 'react'

import { UnframerBreakpoint } from 'unframer'

type Locale = string
export interface Props {
  children?: React.ReactNode
  locale?: Locale
  style?: React.CSSProperties
  className?: string
  id?: string
  width?: any
  height?: any
  layoutId?: string
  variant?: 'Default' | 'Succes (1)' | 'Success (2)' | 'Success (3)'
  padding?: undefined
  title?: string
  subtitle?: string
  label?: string
}

const ContactFormFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & {
  base: Props['variant']
}

ContactFormFramerComponent.Responsive = (
  props: Omit<Props, 'variant'> & { variants?: VariantsMap },
) => any

export default ContactFormFramerComponent
