// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project dfa04aa1c5bdec07 "Jet - SaaS Template (copy)", do not edit manually */
'use client'

import { stdin_default } from './chunks/chunk-QDUJKSXV.js'

// virtual:footer-social-icon
import { Fragment as Fragment2 } from 'react'
import { ContextProviders } from 'unframer'

// /:https://framerusercontent.com/modules/mdWSe0qDhzvo8tYoD1ES/mBwuIhO8DMWIT4lxolCJ/Yk1yNOa0m.js
import { jsx as _jsx } from 'react/jsx-runtime'
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Instance,
  Link,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer'
import { LayoutGroup, motion, MotionConfigContext } from 'unframer'
import * as React from 'react'
import { useRef } from 'react'
var enabledGestures = {
  b18YwARAu: {
    hover: true,
  },
}
var serializationHash = 'framer-CNEL9'
var variantClassNames = {
  b18YwARAu: 'framer-v-1uy76wr',
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]))
  return nextOverrides
}
var convertFromBoolean = (value, activeLocale) => {
  if (value) {
    return '9px 9px 9px 0px'
  } else {
    return '9px'
  }
}
var numberToPixelString = (value) => {
  if (typeof value !== 'number') return value
  if (!Number.isFinite(value)) return void 0
  return Math.max(0, value) + 'px'
}
var transition1 = {
  bounce: 0,
  delay: 0,
  duration: 0.2,
  type: 'spring',
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}
var Variants = motion.create(React.Fragment)
var getProps = ({ height, icon, id, left, link, width, ...props }) => {
  return {
    ...props,
    c2VqnRFYq: icon ?? props.c2VqnRFYq ?? stdin_default,
    fJM58pn7n: left ?? props.fJM58pn7n,
    Uw8EvMv3n: link ?? props.Uw8EvMv3n,
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const { style, className, layoutId, variant, c2VqnRFYq, Uw8EvMv3n, fJM58pn7n, ...restProps } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: 'b18YwARAu',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = []
  const padding = numberToPixelString(convertFromBoolean(fJM58pn7n, activeLocale))
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const Icon = c2VqnRFYq
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link href={Uw8EvMv3n} motionChild={true} nodeId={'b18YwARAu'} scopeId={'Yk1yNOa0m'}>
            <motion.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx(scopingClassNames, 'framer-1uy76wr', className, classNames)} framer-16wncw1`}
              data-framer-name={'Default'}
              layoutDependency={layoutDependency}
              layoutId={'b18YwARAu'}
              ref={refBinding}
              style={{
                '--10ocmuz': padding,
                ...style,
              }}
              {...addPropertyOverrides(
                {
                  'b18YwARAu-hover': {
                    'data-framer-name': void 0,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <Instance
                animated={true}
                className={'framer-shz7sd'}
                Component={Icon}
                layoutDependency={layoutDependency}
                layoutId={'tPeNeA2fA'}
                style={{
                  '--1ya7007': 'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))',
                  scale: 1,
                }}
                variants={{
                  'b18YwARAu-hover': {
                    '--1ya7007': 'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                    scale: 1.075,
                  },
                }}
              />
            </motion.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-CNEL9.framer-16wncw1, .framer-CNEL9 .framer-16wncw1 { display: block; }',
  '.framer-CNEL9.framer-1uy76wr { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: var(--10ocmuz); position: relative; text-decoration: none; width: min-content; }',
  '.framer-CNEL9 .framer-shz7sd { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }',
]
var FramerYk1yNOa0m = withCSS(Component, css, 'framer-CNEL9')
var stdin_default2 = FramerYk1yNOa0m
FramerYk1yNOa0m.displayName = 'Footer Social Icon'
FramerYk1yNOa0m.defaultProps = {
  height: 34,
  width: 34,
}
addPropertyControls(FramerYk1yNOa0m, {
  c2VqnRFYq: {
    defaultValue: {
      identifier: 'local-module:vector/jKWSttf4Z:default',
      moduleId: 'Meigo5pmxENwEjV76TsP',
    },
    setModuleId: 'aQnQxeoODni4mc6H6kTs',
    title: 'Icon',
    type: ControlType.VectorSetItem,
  },
  Uw8EvMv3n: {
    title: 'Link',
    type: ControlType.Link,
  },
  fJM58pn7n: {
    defaultValue: false,
    description: 'Toggle to remove left padding.',
    title: 'Left',
    type: ControlType.Boolean,
  },
})
addFonts(
  FramerYk1yNOa0m,
  [
    {
      explicitInter: true,
      fonts: [],
    },
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// virtual:footer-social-icon
import { WithFramerBreakpoints } from 'unframer'
import { jsx } from 'react/jsx-runtime'
var locales = []
var defaultResponsiveVariants = {}
stdin_default2.Responsive = ({ locale, ...rest }) => {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints Component={stdin_default2} variants={defaultResponsiveVariants} {...rest} />
    </ContextProviders>
  )
}
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default2, {
        ...rest,
      })}
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default2)
export { ComponentWithRoot as default }
