// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project dfa04aa1c5bdec07 "Jet - SaaS Template (copy)", do not edit manually */
'use client'

import {
  className as className3,
  className2 as className4,
  css as css3,
  css2 as css4,
  fonts as fonts3,
  fonts2 as fonts4,
  stdin_default as stdin_default4,
  stdin_default2 as stdin_default5,
  stdin_default3 as stdin_default6,
} from './chunks/chunk-UYAMYDKQ.js'
import { stdin_default as stdin_default2 } from './chunks/chunk-4DXVMHPR.js'
import { stdin_default as stdin_default3 } from './chunks/chunk-6NT3LKTJ.js'
import './chunks/chunk-3XATMP2V.js'
import { className as className2, css as css2, fonts as fonts2 } from './chunks/chunk-ZDI2BEME.js'
import { TextGlitch } from './chunks/chunk-6NDTNB7L.js'
import { className, css, fonts } from './chunks/chunk-JWNC3KJW.js'
import './chunks/chunk-MFJ4W77Q.js'
import './chunks/chunk-FBRPPHGN.js'
import './chunks/chunk-OUEV7UWA.js'
import './chunks/chunk-6NFSISF2.js'
import './chunks/chunk-EAOTBDPC.js'
import { stdin_default } from './chunks/chunk-ALVRX4HO.js'
import { DashedBorderFrame } from './chunks/chunk-R527CHIA.js'
import './chunks/chunk-QKWA2WC3.js'

// virtual:pricing-card
import { Fragment as Fragment2 } from 'react'
import { ContextProviders } from 'unframer'

// /:https://framerusercontent.com/modules/r9vlSp1qAm5WlS8NvHMc/sCR337cKUC61u7XYjQVB/d6KSYM1bo.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime'
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Instance,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer'
import { LayoutGroup, motion, MotionConfigContext } from 'unframer'
import * as React from 'react'
import { useRef } from 'react'
var MainSiteGridBorderFonts = getFonts(stdin_default)
var TagFonts = getFonts(stdin_default6)
var AnimatedDashedBorderFonts = getFonts(DashedBorderFrame)
var TextGlitchFonts = getFonts(TextGlitch)
var CheckItemFonts = getFonts(stdin_default5)
var ButtonNoLinkFonts = getFonts(stdin_default4)
var CardSelectorFonts = getFonts(stdin_default2)
var enabledGestures = {
  IgCIax3De: {
    hover: true,
  },
  y6WhJFtlo: {
    hover: true,
  },
}
var cycleOrder = ['y6WhJFtlo', 'IgCIax3De', 'c5QXex2mF', 'xN6JCzUC3']
var serializationHash = 'framer-Rzpcg'
var variantClassNames = {
  c5QXex2mF: 'framer-v-ydx9z9',
  IgCIax3De: 'framer-v-15ekuat',
  xN6JCzUC3: 'framer-v-3a44eu',
  y6WhJFtlo: 'framer-v-q9079d',
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]))
  return nextOverrides
}
var transition1 = {
  bounce: 0,
  delay: 0,
  duration: 0.4,
  type: 'spring',
}
var convertFromBoolean = (value, activeLocale) => {
  if (value) {
    return 'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)) /* {"name":"Accent"} */'
  } else {
    return 'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255)) /* {"name":"White"} */'
  }
}
var toString = (value) => {
  return typeof value === 'string' ? value : String(value)
}
var negate = (value) => {
  return !value
}
var convertFromBoolean1 = (value, activeLocale) => {
  if (value) {
    return 'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)) /* {"name":"Accent"} */'
  } else {
    return 'var(--token-361e1224-4029-4612-a297-51f349511b71, rgba(255, 255, 255, 0.1)) /* {"name":"10% White"} */'
  }
}
var isSet = (value) => {
  if (Array.isArray(value)) return value.length > 0
  return value !== void 0 && value !== null && value !== ''
}
var convertFromBoolean2 = (value, activeLocale) => {
  if (value) {
    return 'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)) /* {"name":"Accent"} */'
  } else {
    return 'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)) /* {"name":"50% White"} */'
  }
}
var convertFromBoolean3 = (value, activeLocale) => {
  if (value) {
    return 'apqsHcFhe'
  } else {
    return 'l5ER7h9wM'
  }
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  'Monthly Mobile': 'xN6JCzUC3',
  'Yearly Mobile': 'c5QXex2mF',
  Monhtly: 'IgCIax3De',
  Yearly: 'y6WhJFtlo',
}
var getProps = ({
  cTA,
  currency,
  description,
  feature1,
  feature2,
  feature3,
  feature4,
  feature5,
  free,
  height,
  icon,
  id,
  link,
  name1,
  popular,
  price1,
  price2,
  width,
  ...props
}) => {
  return {
    ...props,
    As9JzxDIJ: link ?? props.As9JzxDIJ,
    AwtItklIa: description ?? props.AwtItklIa ?? 'Perfect for personal projects\u2014speed up one site for free.\xA0',
    bUDolueJu: popular ?? props.bUDolueJu,
    Da10mBQeK: feature4 ?? props.Da10mBQeK,
    l5kvMSOyG: cTA ?? props.l5kvMSOyG ?? 'Get started',
    NoMO2P6IN: feature3 ?? props.NoMO2P6IN ?? 'Limited analytics',
    o6Najb0WK: free ?? props.o6Najb0WK,
    P0K_zeDf2: price1 ?? props.P0K_zeDf2 ?? '24',
    rEMZqr2nD: feature2 ?? props.rEMZqr2nD ?? 'Basic image & code optimization',
    sx9umVdGi: name1 ?? props.sx9umVdGi ?? 'Starter',
    UlbULOgWO: currency ?? props.UlbULOgWO ?? '$',
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'y6WhJFtlo',
    vr9PizPKy: feature1 ?? props.vr9PizPKy ?? '1 website',
    xTbjfjg0x: feature5 ?? props.xTbjfjg0x,
    yF7yl7gwH: icon ?? props.yF7yl7gwH ?? stdin_default3,
    ZGLiCBQwm: price2 ?? props.ZGLiCBQwm ?? '29',
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className5,
    layoutId,
    variant,
    o6Najb0WK,
    bUDolueJu,
    yF7yl7gwH,
    sx9umVdGi,
    AwtItklIa,
    UlbULOgWO,
    P0K_zeDf2,
    ZGLiCBQwm,
    l5kvMSOyG,
    As9JzxDIJ,
    vr9PizPKy,
    rEMZqr2nD,
    NoMO2P6IN,
    Da10mBQeK,
    xTbjfjg0x,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'y6WhJFtlo',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className3, className, className2, className4]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const visible = negate(o6Najb0WK)
  const isDisplayed = () => {
    if (gestureVariant === 'IgCIax3De-hover') return false
    if (['IgCIax3De', 'xN6JCzUC3'].includes(baseVariant)) return false
    return true
  }
  const isDisplayed1 = () => {
    if (gestureVariant === 'IgCIax3De-hover') return true
    if (['IgCIax3De', 'xN6JCzUC3'].includes(baseVariant)) return true
    return false
  }
  const fillColor = toString(convertFromBoolean1(bUDolueJu, activeLocale))
  const visible1 = isSet(vr9PizPKy)
  const visible2 = isSet(rEMZqr2nD)
  const visible3 = isSet(NoMO2P6IN)
  const visible4 = isSet(Da10mBQeK)
  const visible5 = isSet(xTbjfjg0x)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link href={As9JzxDIJ} motionChild={true} nodeId={'y6WhJFtlo'} scopeId={'d6KSYM1bo'}>
            <motion.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx(scopingClassNames, 'framer-q9079d', className5, classNames)} framer-x96clp`}
              data-framer-name={'Yearly'}
              layoutDependency={layoutDependency}
              layoutId={'y6WhJFtlo'}
              ref={refBinding}
              style={{
                ...style,
              }}
              {...addPropertyOverrides(
                {
                  'IgCIax3De-hover': {
                    'data-framer-name': void 0,
                  },
                  'y6WhJFtlo-hover': {
                    'data-framer-name': void 0,
                  },
                  c5QXex2mF: {
                    'data-framer-name': 'Yearly Mobile',
                  },
                  IgCIax3De: {
                    'data-framer-name': 'Monhtly',
                  },
                  xN6JCzUC3: {
                    'data-framer-name': 'Monthly Mobile',
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <ComponentViewportProvider
                height={(componentViewport?.height || 500) - 0}
                width={componentViewport?.width || '100vw'}
                y={(componentViewport?.y || 0) + 0}
                {...addPropertyOverrides(
                  {
                    c5QXex2mF: {
                      height: (componentViewport?.height || 440) - 0,
                    },
                    xN6JCzUC3: {
                      height: (componentViewport?.height || 440) - 0,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                )}
              >
                <SmartComponentScopedContainer
                  className={'framer-19vkkye-container'}
                  layoutDependency={layoutDependency}
                  layoutId={'huEGMXHvh-container'}
                  nodeId={'huEGMXHvh'}
                  rendersWithMotion={true}
                  scopeId={'d6KSYM1bo'}
                >
                  {_jsx(stdin_default, {
                    height: '100%',
                    id: 'huEGMXHvh',
                    layoutId: 'huEGMXHvh',
                    style: {
                      height: '100%',
                      width: '100%',
                    },
                    variant: 'yzIFdYlxZ',
                    width: '100%',
                  })}
                </SmartComponentScopedContainer>
              </ComponentViewportProvider>
              <motion.div
                className={'framer-lwn2r7'}
                data-framer-name={'Text'}
                layoutDependency={layoutDependency}
                layoutId={'gbZ8r6ZAE'}
              >
                <motion.div
                  className={'framer-1uamcid'}
                  data-framer-name={'Name + Tag'}
                  layoutDependency={layoutDependency}
                  layoutId={'RORPo7Zjz'}
                >
                  <Instance
                    animated={true}
                    className={'framer-1cbqvub'}
                    Component={yF7yl7gwH}
                    layoutDependency={layoutDependency}
                    layoutId={'JrMHtINEm'}
                    style={{
                      '--ikhcm7': toString(convertFromBoolean(bUDolueJu, activeLocale)),
                    }}
                  />
                  <RichText
                    __fromCanvasComponent={true}
                    className={'framer-1hb72sm'}
                    fonts={['Inter']}
                    layoutDependency={layoutDependency}
                    layoutId={'CoBEjzKd4'}
                    style={{
                      '--framer-link-text-color': 'rgb(0, 153, 255)',
                      '--framer-link-text-decoration': 'underline',
                    }}
                    text={sx9umVdGi}
                    verticalAlignment={'top'}
                    withExternalLayout={true}
                  >
                    <React.Fragment>
                      <motion.p className={'framer-styles-preset-1gyvw87'} data-styles-preset={'hWxVRiaNu'}>
                        {'Starter'}
                      </motion.p>
                    </React.Fragment>
                  </RichText>
                  {bUDolueJu && (
                    <ComponentViewportProvider height={24} y={(componentViewport?.y || 0) + 34 + 0 + 0 + 0 + 63}>
                      <SmartComponentScopedContainer
                        className={'framer-19z08hm-container'}
                        layoutDependency={layoutDependency}
                        layoutId={'NC6rY7G_8-container'}
                        nodeId={'NC6rY7G_8'}
                        rendersWithMotion={true}
                        scopeId={'d6KSYM1bo'}
                      >
                        {_jsx(stdin_default6, {
                          height: '100%',
                          id: 'NC6rY7G_8',
                          layoutId: 'NC6rY7G_8',
                          NjOVpa_TO: true,
                          qVFnPYB39: 'Most popular',
                          style: {
                            height: '100%',
                          },
                          variant: 'PkLBxMzqm',
                          width: '100%',
                        })}
                      </SmartComponentScopedContainer>
                    </ComponentViewportProvider>
                  )}
                </motion.div>
                <RichText
                  __fromCanvasComponent={true}
                  className={'framer-1kqs8l7'}
                  fonts={['Inter']}
                  layoutDependency={layoutDependency}
                  layoutId={'awOanS0Sd'}
                  style={{
                    '--extracted-r6o4lv': 'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))',
                    '--framer-link-text-color': 'rgb(0, 153, 255)',
                    '--framer-link-text-decoration': 'underline',
                  }}
                  text={AwtItklIa}
                  verticalAlignment={'top'}
                  withExternalLayout={true}
                >
                  <React.Fragment>
                    <motion.p
                      className={'framer-styles-preset-c9mga6'}
                      data-styles-preset={'Xa6VJQy2p'}
                      style={{
                        '--framer-text-color':
                          'var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))',
                      }}
                    >
                      {'Perfect for personal projects\u2014speed up one site for free.\xA0'}
                    </motion.p>
                  </React.Fragment>
                </RichText>
              </motion.div>
              {o6Najb0WK && (
                <motion.div
                  className={'framer-1akggtt'}
                  data-framer-name={'Tag'}
                  layoutDependency={layoutDependency}
                  layoutId={'UwOvimh9S'}
                  style={{
                    backgroundColor: 'var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))',
                    borderBottomLeftRadius: 100,
                    borderBottomRightRadius: 100,
                    borderTopLeftRadius: 100,
                    borderTopRightRadius: 100,
                  }}
                >
                  <RichText
                    __fromCanvasComponent={true}
                    className={'framer-pbww0f'}
                    fonts={['Inter']}
                    layoutDependency={layoutDependency}
                    layoutId={'yNClFTzFZ'}
                    style={{
                      '--extracted-r6o4lv':
                        'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))',
                      '--framer-link-text-color': 'rgb(0, 153, 255)',
                      '--framer-link-text-decoration': 'underline',
                    }}
                    verticalAlignment={'top'}
                    withExternalLayout={true}
                  >
                    <React.Fragment>
                      <motion.p
                        className={'framer-styles-preset-d4fts2'}
                        data-styles-preset={'bRzBDjLMv'}
                        style={{
                          '--framer-text-color':
                            'var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))',
                        }}
                      >
                        {'Free forever'}
                      </motion.p>
                    </React.Fragment>
                  </RichText>
                  <ComponentViewportProvider>
                    <SmartComponentScopedContainer
                      className={'framer-mkaczq-container'}
                      isAuthoredByUser={true}
                      isModuleExternal={true}
                      layoutDependency={layoutDependency}
                      layoutId={'oWjsTHCDL-container'}
                      nodeId={'oWjsTHCDL'}
                      rendersWithMotion={true}
                      scopeId={'d6KSYM1bo'}
                    >
                      <DashedBorderFrame
                        animation={{
                          animated: true,
                          direction: 'clockwise',
                          speed: 2,
                        }}
                        borderColor={'var(--token-04a04e54-cbd8-4312-8418-e1527ef396e1, rgb(51, 51, 51))'}
                        borderRadius={20}
                        borderWidth={1}
                        bottom={true}
                        dashLength={6}
                        gapLength={4}
                        height={'100%'}
                        id={'oWjsTHCDL'}
                        layoutId={'oWjsTHCDL'}
                        left={true}
                        right={true}
                        style={{
                          height: '100%',
                          width: '100%',
                        }}
                        top={true}
                        width={'100%'}
                      />
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                </motion.div>
              )}
              {visible && (
                <motion.div
                  className={'framer-14p7x0z'}
                  data-framer-name={'Price'}
                  layoutDependency={layoutDependency}
                  layoutId={'ZnzMnEXzn'}
                >
                  <motion.div
                    className={'framer-av70u1'}
                    data-framer-name={'Number'}
                    layoutDependency={layoutDependency}
                    layoutId={'fJv7A2e2O'}
                  >
                    <RichText
                      __fromCanvasComponent={true}
                      className={'framer-17vyf5n'}
                      fonts={['Inter']}
                      layoutDependency={layoutDependency}
                      layoutId={'yazBsZjxM'}
                      style={{
                        '--framer-link-text-color': 'rgb(0, 153, 255)',
                        '--framer-link-text-decoration': 'underline',
                      }}
                      text={UlbULOgWO}
                      verticalAlignment={'top'}
                      withExternalLayout={true}
                    >
                      <React.Fragment>
                        <motion.p className={'framer-styles-preset-19gotht'} data-styles-preset={'PnqQKY4Hn'}>
                          {'$'}
                        </motion.p>
                      </React.Fragment>
                    </RichText>
                    {isDisplayed() && (
                      <ComponentViewportProvider>
                        <SmartComponentScopedContainer
                          className={'framer-1fbih4t-container'}
                          data-framer-name={'Yearly'}
                          isAuthoredByUser={true}
                          isModuleExternal={true}
                          layoutDependency={layoutDependency}
                          layoutId={'vQoSR4hud-container'}
                          name={'Yearly'}
                          nodeId={'vQoSR4hud'}
                          rendersWithMotion={true}
                          scopeId={'d6KSYM1bo'}
                        >
                          <TextGlitch
                            color={'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))'}
                            duration={500}
                            font={{
                              fontFamily: '"Raveo Variable Variable", sans-serif',
                              fontFeatureSettings: "'tnum' on",
                              fontSize: '30px',
                              fontStyle: 'normal',
                              fontWeight: 1e3,
                              letterSpacing: '-0.01em',
                              lineHeight: '1.3em',
                              textAlign: 'left',
                            }}
                            glitch={true}
                            height={'100%'}
                            id={'vQoSR4hud'}
                            layoutId={'vQoSR4hud'}
                            name={'Yearly'}
                            scrambleChars={'1234567890'}
                            scrambleColor={
                              'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))'
                            }
                            scramblePercent={50}
                            speed={40}
                            text={P0K_zeDf2}
                            variable={{
                              optical: 14,
                              weight: 550,
                            }}
                            width={'100%'}
                          />
                        </SmartComponentScopedContainer>
                      </ComponentViewportProvider>
                    )}
                    {isDisplayed1() && (
                      <ComponentViewportProvider>
                        <SmartComponentScopedContainer
                          className={'framer-drbbvn-container'}
                          data-framer-name={'Monthly'}
                          isAuthoredByUser={true}
                          isModuleExternal={true}
                          layoutDependency={layoutDependency}
                          layoutId={'fEb8Ziohb-container'}
                          name={'Monthly'}
                          nodeId={'fEb8Ziohb'}
                          rendersWithMotion={true}
                          scopeId={'d6KSYM1bo'}
                        >
                          <TextGlitch
                            color={'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))'}
                            duration={500}
                            font={{
                              fontFamily: '"Raveo Variable Variable", sans-serif',
                              fontFeatureSettings: "'tnum' on",
                              fontSize: '30px',
                              fontStyle: 'normal',
                              fontWeight: 1e3,
                              letterSpacing: '-0.01em',
                              lineHeight: '1.3em',
                              textAlign: 'left',
                            }}
                            glitch={true}
                            height={'100%'}
                            id={'fEb8Ziohb'}
                            layoutId={'fEb8Ziohb'}
                            name={'Monthly'}
                            scrambleChars={'1234567890'}
                            scrambleColor={
                              'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))'
                            }
                            scramblePercent={50}
                            speed={40}
                            text={ZGLiCBQwm}
                            variable={{
                              optical: 14,
                              weight: 550,
                            }}
                            width={'100%'}
                          />
                        </SmartComponentScopedContainer>
                      </ComponentViewportProvider>
                    )}
                  </motion.div>
                  <motion.div
                    className={'framer-1ou1697'}
                    data-framer-name={'Wrapper'}
                    layoutDependency={layoutDependency}
                    layoutId={'OnhzkePxT'}
                  >
                    <RichText
                      __fromCanvasComponent={true}
                      className={'framer-m5za82'}
                      fonts={['Inter']}
                      layoutDependency={layoutDependency}
                      layoutId={'nAU4nLPfV'}
                      style={{
                        '--extracted-r6o4lv':
                          'var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5))',
                        '--framer-link-text-color': 'rgb(0, 153, 255)',
                        '--framer-link-text-decoration': 'underline',
                      }}
                      verticalAlignment={'top'}
                      withExternalLayout={true}
                      {...addPropertyOverrides(
                        {
                          IgCIax3De: {
                            children: (
                              <React.Fragment>
                                <motion.p
                                  className={'framer-styles-preset-c9mga6'}
                                  data-styles-preset={'Xa6VJQy2p'}
                                  style={{
                                    '--framer-text-color':
                                      'var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))',
                                  }}
                                >
                                  {'/month'}
                                </motion.p>
                              </React.Fragment>
                            ),
                          },
                          xN6JCzUC3: {
                            children: (
                              <React.Fragment>
                                <motion.p
                                  className={'framer-styles-preset-c9mga6'}
                                  data-styles-preset={'Xa6VJQy2p'}
                                  style={{
                                    '--framer-text-color':
                                      'var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))',
                                  }}
                                >
                                  {'/month'}
                                </motion.p>
                              </React.Fragment>
                            ),
                          },
                        },
                        baseVariant,
                        gestureVariant,
                      )}
                    >
                      <React.Fragment>
                        <motion.p
                          className={'framer-styles-preset-c9mga6'}
                          data-styles-preset={'Xa6VJQy2p'}
                          style={{
                            '--framer-text-color':
                              'var(--extracted-r6o4lv, var(--token-8acf10b0-fc55-42ff-8ac5-80a79dc47979, rgba(255, 255, 255, 0.5)))',
                          }}
                        >
                          {'/month, billed annually'}
                        </motion.p>
                      </React.Fragment>
                    </RichText>
                  </motion.div>
                </motion.div>
              )}
              <motion.div
                className={'framer-10js6c1'}
                data-framer-name={'Divider'}
                layoutDependency={layoutDependency}
                layoutId={'RGOsW5e3j'}
                style={{
                  backgroundColor: fillColor,
                }}
              />
              <motion.div
                className={'framer-1lv2k16'}
                data-framer-name={'Features'}
                layoutDependency={layoutDependency}
                layoutId={'cRw7J01js'}
              >
                {visible1 && (
                  <ComponentViewportProvider
                    height={34}
                    width={`calc(${componentViewport?.width || '100vw'} - 68px)`}
                    y={(componentViewport?.y || 0) + 34 + 621 + 8 + 0}
                  >
                    <SmartComponentScopedContainer
                      className={'framer-1abpsgg-container'}
                      layoutDependency={layoutDependency}
                      layoutId={'Hfv8kXdsF-container'}
                      nodeId={'Hfv8kXdsF'}
                      rendersWithMotion={true}
                      scopeId={'d6KSYM1bo'}
                    >
                      {_jsx(stdin_default5, {
                        GmEwQyBsT: vr9PizPKy,
                        height: '100%',
                        id: 'Hfv8kXdsF',
                        layoutId: 'Hfv8kXdsF',
                        style: {
                          width: '100%',
                        },
                        UYqIbOuBm: toString(convertFromBoolean2(bUDolueJu, activeLocale)),
                        variant: 'JzWLJacCt',
                        width: '100%',
                      })}
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                )}
                {visible2 && (
                  <ComponentViewportProvider
                    height={34}
                    width={`calc(${componentViewport?.width || '100vw'} - 68px)`}
                    y={(componentViewport?.y || 0) + 34 + 621 + 8 + 42}
                  >
                    <SmartComponentScopedContainer
                      className={'framer-1drxexp-container'}
                      layoutDependency={layoutDependency}
                      layoutId={'MubfsfgqE-container'}
                      nodeId={'MubfsfgqE'}
                      rendersWithMotion={true}
                      scopeId={'d6KSYM1bo'}
                    >
                      {_jsx(stdin_default5, {
                        GmEwQyBsT: rEMZqr2nD,
                        height: '100%',
                        id: 'MubfsfgqE',
                        layoutId: 'MubfsfgqE',
                        style: {
                          width: '100%',
                        },
                        UYqIbOuBm: toString(convertFromBoolean2(bUDolueJu, activeLocale)),
                        variant: 'JzWLJacCt',
                        width: '100%',
                      })}
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                )}
                {visible3 && (
                  <ComponentViewportProvider
                    height={34}
                    width={`calc(${componentViewport?.width || '100vw'} - 68px)`}
                    y={(componentViewport?.y || 0) + 34 + 621 + 8 + 84}
                  >
                    <SmartComponentScopedContainer
                      className={'framer-e5glma-container'}
                      layoutDependency={layoutDependency}
                      layoutId={'FVDOIkbMF-container'}
                      nodeId={'FVDOIkbMF'}
                      rendersWithMotion={true}
                      scopeId={'d6KSYM1bo'}
                    >
                      {_jsx(stdin_default5, {
                        GmEwQyBsT: NoMO2P6IN,
                        height: '100%',
                        id: 'FVDOIkbMF',
                        layoutId: 'FVDOIkbMF',
                        style: {
                          width: '100%',
                        },
                        UYqIbOuBm: toString(convertFromBoolean2(bUDolueJu, activeLocale)),
                        variant: 'JzWLJacCt',
                        width: '100%',
                      })}
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                )}
                {visible4 && (
                  <ComponentViewportProvider
                    height={34}
                    width={`calc(${componentViewport?.width || '100vw'} - 68px)`}
                    y={(componentViewport?.y || 0) + 34 + 621 + 8 + 126}
                  >
                    <SmartComponentScopedContainer
                      className={'framer-1c9115y-container'}
                      layoutDependency={layoutDependency}
                      layoutId={'rWGtCbDx0-container'}
                      nodeId={'rWGtCbDx0'}
                      rendersWithMotion={true}
                      scopeId={'d6KSYM1bo'}
                    >
                      {_jsx(stdin_default5, {
                        GmEwQyBsT: Da10mBQeK,
                        height: '100%',
                        id: 'rWGtCbDx0',
                        layoutId: 'rWGtCbDx0',
                        style: {
                          width: '100%',
                        },
                        UYqIbOuBm: toString(convertFromBoolean2(bUDolueJu, activeLocale)),
                        variant: 'JzWLJacCt',
                        width: '100%',
                      })}
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                )}
                {visible5 && (
                  <ComponentViewportProvider
                    height={34}
                    width={`calc(${componentViewport?.width || '100vw'} - 68px)`}
                    y={(componentViewport?.y || 0) + 34 + 621 + 8 + 168}
                  >
                    <SmartComponentScopedContainer
                      className={'framer-1llzp7e-container'}
                      layoutDependency={layoutDependency}
                      layoutId={'E07st1DQV-container'}
                      nodeId={'E07st1DQV'}
                      rendersWithMotion={true}
                      scopeId={'d6KSYM1bo'}
                    >
                      {_jsx(stdin_default5, {
                        GmEwQyBsT: xTbjfjg0x,
                        height: '100%',
                        id: 'E07st1DQV',
                        layoutId: 'E07st1DQV',
                        style: {
                          width: '100%',
                        },
                        UYqIbOuBm: toString(convertFromBoolean2(bUDolueJu, activeLocale)),
                        variant: 'JzWLJacCt',
                        width: '100%',
                      })}
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                )}
              </motion.div>
              <ComponentViewportProvider
                height={40}
                width={`calc(${componentViewport?.width || '100vw'} - 68px)`}
                y={
                  (componentViewport?.y || 0) +
                  34 +
                  (0 +
                    (275 + 40 + 200 + 2 + Math.max(0, ((componentViewport?.height || 500) - 68 - 687 - 0) / 1) * 1) +
                    130)
                }
                {...addPropertyOverrides(
                  {
                    c5QXex2mF: {
                      y: (componentViewport?.y || 0) + 34 + 781,
                    },
                    xN6JCzUC3: {
                      y: (componentViewport?.y || 0) + 34 + 781,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                )}
              >
                <SmartComponentScopedContainer
                  className={'framer-13xftm0-container'}
                  layoutDependency={layoutDependency}
                  layoutId={'N_H3EOK48-container'}
                  nodeId={'N_H3EOK48'}
                  rendersWithMotion={true}
                  scopeId={'d6KSYM1bo'}
                >
                  {_jsx(stdin_default4, {
                    D9dBYabSn: true,
                    height: '100%',
                    id: 'N_H3EOK48',
                    layoutId: 'N_H3EOK48',
                    qCxNvGxTB: 'Default',
                    SMZpJms0Q: l5kvMSOyG,
                    style: {
                      height: '100%',
                      width: '100%',
                    },
                    variant: convertFromBoolean3(bUDolueJu, activeLocale),
                    width: '100%',
                    ...addPropertyOverrides(
                      {
                        'IgCIax3De-hover': {
                          qCxNvGxTB: 'Roll',
                        },
                        'y6WhJFtlo-hover': {
                          qCxNvGxTB: 'Roll',
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  })}
                </SmartComponentScopedContainer>
              </ComponentViewportProvider>
              <ComponentViewportProvider
                height={(componentViewport?.height || 500) - 0}
                width={componentViewport?.width || '100vw'}
                y={(componentViewport?.y || 0) + 0}
                {...addPropertyOverrides(
                  {
                    c5QXex2mF: {
                      height: (componentViewport?.height || 440) - 0,
                    },
                    xN6JCzUC3: {
                      height: (componentViewport?.height || 440) - 0,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                )}
              >
                <SmartComponentScopedContainer
                  className={'framer-yw0evy-container'}
                  layoutDependency={layoutDependency}
                  layoutId={'E2fwsyC0k-container'}
                  nodeId={'E2fwsyC0k'}
                  rendersWithMotion={true}
                  scopeId={'d6KSYM1bo'}
                >
                  {_jsx(stdin_default2, {
                    height: '100%',
                    id: 'E2fwsyC0k',
                    layoutId: 'E2fwsyC0k',
                    style: {
                      height: '100%',
                      width: '100%',
                    },
                    variant: 'jcOPzl09p',
                    width: '100%',
                    ...addPropertyOverrides(
                      {
                        'IgCIax3De-hover': {
                          variant: 'CCKwLQUhX',
                        },
                        'y6WhJFtlo-hover': {
                          variant: 'CCKwLQUhX',
                        },
                      },
                      baseVariant,
                      gestureVariant,
                    ),
                  })}
                </SmartComponentScopedContainer>
              </ComponentViewportProvider>
            </motion.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css5 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-Rzpcg.framer-x96clp, .framer-Rzpcg .framer-x96clp { display: block; }',
  '.framer-Rzpcg.framer-q9079d { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: 500px; justify-content: flex-start; overflow: visible; padding: 34px; position: relative; text-decoration: none; width: 390px; }',
  '.framer-Rzpcg .framer-19vkkye-container { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; z-index: 2; }',
  '.framer-Rzpcg .framer-lwn2r7 { -webkit-user-select: none; align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; user-select: none; width: 100%; z-index: 2; }',
  '.framer-Rzpcg .framer-1uamcid { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-Rzpcg .framer-1cbqvub { flex: none; height: var(--framer-aspect-ratio-supported, 28px); position: relative; width: 28px; }',
  '.framer-Rzpcg .framer-1hb72sm, .framer-Rzpcg .framer-m5za82 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }',
  '.framer-Rzpcg .framer-19z08hm-container { flex: none; height: 24px; position: relative; width: auto; z-index: 2; }',
  '.framer-Rzpcg .framer-1kqs8l7 { flex: none; height: auto; max-width: 240px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-Rzpcg .framer-1akggtt { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: hidden; padding: 0px 16px 0px 16px; position: relative; user-select: none; width: min-content; will-change: var(--framer-will-change-override, transform); }',
  '.framer-Rzpcg .framer-pbww0f, .framer-Rzpcg .framer-17vyf5n { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-Rzpcg .framer-mkaczq-container { bottom: 0px; flex: none; left: 0px; pointer-events: none; position: absolute; right: 0px; top: 0px; z-index: 1; }',
  '.framer-Rzpcg .framer-14p7x0z { -webkit-user-select: none; align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; user-select: none; width: 100%; }',
  '.framer-Rzpcg .framer-av70u1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }',
  '.framer-Rzpcg .framer-1fbih4t-container, .framer-Rzpcg .framer-drbbvn-container { flex: none; height: auto; position: relative; width: auto; }',
  '.framer-Rzpcg .framer-1ou1697 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 4px 0px; position: relative; width: 1px; }',
  '.framer-Rzpcg .framer-10js6c1 { flex: none; height: 2px; overflow: hidden; position: relative; width: 100%; }',
  '.framer-Rzpcg .framer-1lv2k16 { -webkit-user-select: none; align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 1px; justify-content: flex-start; overflow: hidden; padding: 8px 0px 0px 0px; position: relative; user-select: none; width: 100%; }',
  '.framer-Rzpcg .framer-1abpsgg-container, .framer-Rzpcg .framer-1drxexp-container, .framer-Rzpcg .framer-e5glma-container, .framer-Rzpcg .framer-1c9115y-container, .framer-Rzpcg .framer-1llzp7e-container { flex: none; height: auto; position: relative; width: 100%; }',
  '.framer-Rzpcg .framer-13xftm0-container { flex: none; height: 40px; position: relative; width: 100%; }',
  '.framer-Rzpcg .framer-yw0evy-container { -webkit-user-select: none; bottom: 0px; flex: none; left: 0px; pointer-events: none; position: absolute; right: 0px; top: 0px; user-select: none; z-index: 4; }',
  '.framer-Rzpcg.framer-v-ydx9z9.framer-q9079d, .framer-Rzpcg.framer-v-3a44eu.framer-q9079d { height: min-content; }',
  '.framer-Rzpcg.framer-v-ydx9z9 .framer-1lv2k16, .framer-Rzpcg.framer-v-3a44eu .framer-1lv2k16 { flex: none; height: min-content; padding: 8px 0px 8px 0px; }',
  ...css3,
  ...css,
  ...css2,
  ...css4,
]
var Framerd6KSYM1bo = withCSS(Component, css5, 'framer-Rzpcg')
var stdin_default7 = Framerd6KSYM1bo
Framerd6KSYM1bo.displayName = 'Pricing Card'
Framerd6KSYM1bo.defaultProps = {
  height: 500,
  width: 390,
}
addPropertyControls(Framerd6KSYM1bo, {
  variant: {
    options: ['y6WhJFtlo', 'IgCIax3De', 'c5QXex2mF', 'xN6JCzUC3'],
    optionTitles: ['Yearly', 'Monhtly', 'Yearly Mobile', 'Monthly Mobile'],
    title: 'Variant',
    type: ControlType.Enum,
  },
  o6Najb0WK: {
    defaultValue: false,
    title: 'Free',
    type: ControlType.Boolean,
  },
  bUDolueJu: {
    defaultValue: false,
    title: 'Popular',
    type: ControlType.Boolean,
  },
  yF7yl7gwH: {
    defaultValue: {
      identifier: 'local-module:vector/D1US_NPnH:default',
      moduleId: 'mqdwpjiHYIcCcxT5nlJ7',
    },
    setModuleId: 'GjeHhKZr1fFtDLVZKUZs',
    title: 'Icon',
    type: ControlType.VectorSetItem,
  },
  sx9umVdGi: {
    defaultValue: 'Starter',
    displayTextArea: false,
    title: 'Name',
    type: ControlType.String,
  },
  AwtItklIa: {
    defaultValue: 'Perfect for personal projects\u2014speed up one site for free.\xA0',
    displayTextArea: false,
    title: 'Description',
    type: ControlType.String,
  },
  UlbULOgWO: {
    defaultValue: '$',
    displayTextArea: false,
    title: 'Currency',
    type: ControlType.String,
  },
  P0K_zeDf2: {
    defaultValue: '24',
    description: 'Yearly',
    title: 'Price (1)',
    type: ControlType.String,
  },
  ZGLiCBQwm: {
    defaultValue: '29',
    description: 'Monthly',
    title: 'Price (2)',
    type: ControlType.String,
  },
  l5kvMSOyG: {
    defaultValue: 'Get started',
    displayTextArea: false,
    title: 'CTA',
    type: ControlType.String,
  },
  As9JzxDIJ: {
    title: 'Link',
    type: ControlType.Link,
  },
  vr9PizPKy: {
    defaultValue: '1 website',
    displayTextArea: false,
    title: 'Feature 1',
    type: ControlType.String,
  },
  rEMZqr2nD: {
    defaultValue: 'Basic image & code optimization',
    displayTextArea: false,
    title: 'Feature 2',
    type: ControlType.String,
  },
  NoMO2P6IN: {
    defaultValue: 'Limited analytics',
    displayTextArea: false,
    title: 'Feature 3',
    type: ControlType.String,
  },
  Da10mBQeK: {
    defaultValue: '',
    displayTextArea: false,
    title: 'Feature 4',
    type: ControlType.String,
  },
  xTbjfjg0x: {
    defaultValue: '',
    displayTextArea: false,
    placeholder: '',
    title: 'Feature 5',
    type: ControlType.String,
  },
})
var variationAxes = [
  {
    defaultValue: 14,
    maxValue: 32,
    minValue: 14,
    name: 'Optical size',
    tag: 'opsz',
  },
  {
    defaultValue: 400,
    maxValue: 900,
    minValue: 100,
    name: 'Weight',
    tag: 'wght',
  },
]
addFonts(
  Framerd6KSYM1bo,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400',
        },
        {
          family: 'Raveo Variable',
          source: 'builtIn',
          style: 'normal',
          url: 'https://framerusercontent.com/assets/JEdA86oNqHX1i1CLD92Q7jTxV8.woff2',
          variationAxes,
          weight: '1000',
        },
      ],
    },
    ...MainSiteGridBorderFonts,
    ...TagFonts,
    ...AnimatedDashedBorderFonts,
    ...TextGlitchFonts,
    ...CheckItemFonts,
    ...ButtonNoLinkFonts,
    ...CardSelectorFonts,
    ...getFontsFromSharedStyle(fonts3),
    ...getFontsFromSharedStyle(fonts),
    ...getFontsFromSharedStyle(fonts2),
    ...getFontsFromSharedStyle(fonts4),
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// virtual:pricing-card
import { WithFramerBreakpoints } from 'unframer'
import { jsx } from 'react/jsx-runtime'
var locales = []
var defaultResponsiveVariants = {
  base: 'IgCIax3De',
}
stdin_default7.Responsive = ({ locale, ...rest }) => {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints Component={stdin_default7} variants={defaultResponsiveVariants} {...rest} />
    </ContextProviders>
  )
}
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default7, {
        ...rest,
      })}
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default7)
export { ComponentWithRoot as default }
