// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project dfa04aa1c5bdec07 "Jet - SaaS Template (copy)", do not edit manually */
'use client'

import { stdin_default } from './chunks/chunk-BZO7VVQN.js'
import './chunks/chunk-VLMUKI5O.js'
import './chunks/chunk-QKWA2WC3.js'

// virtual:testimonial-cycler
import { Fragment as Fragment2 } from 'react'
import { ContextProviders } from 'unframer'

// /:https://framerusercontent.com/modules/hU6sdHiDHtB254DEbiR0/CFSulJhIwRpDjKVmXpI8/W7wIBXQug.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime'
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer'
import { LayoutGroup, motion, MotionConfigContext } from 'unframer'
import * as React from 'react'
import { useRef } from 'react'
var SmallTestimonialCardFonts = getFonts(stdin_default)
var cycleOrder = ['gXOOgW_0x', 'y4G8oqwNh', 'zhhN81oxS']
var serializationHash = 'framer-AcMmK'
var variantClassNames = {
  gXOOgW_0x: 'framer-v-vy0o8s',
  y4G8oqwNh: 'framer-v-c6hvu7',
  zhhN81oxS: 'framer-v-eav2yx',
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]))
  return nextOverrides
}
var transition1 = {
  duration: 0,
  type: 'tween',
}
var transition2 = {
  bounce: 0,
  delay: 0,
  duration: 0.6,
  type: 'spring',
}
var toResponsiveImage = (value) => {
  if (typeof value === 'object' && value !== null && typeof value.src === 'string') {
    return value
  }
  return typeof value === 'string'
    ? {
        src: value,
      }
    : void 0
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  Back: 'zhhN81oxS',
  Start: 'gXOOgW_0x',
  Switch: 'y4G8oqwNh',
}
var getProps = ({
  color,
  color2,
  height,
  id,
  image,
  image2,
  name1,
  name2,
  role,
  role2,
  testimonial,
  testimonial2,
  width,
  ...props
}) => {
  return {
    ...props,
    BgC3EyFez: color2 ?? props.BgC3EyFez ?? 'var(--token-1e61b8ec-fb03-4d71-8889-99c84f72af30, rgb(216, 92, 224))',
    BkVgYZ4LQ: role ?? props.BkVgYZ4LQ ?? 'E-commerce Owner',
    ELlerrEJz: name1 ?? props.ELlerrEJz ?? 'Luca Rossi',
    GCneHTBce: name2 ?? props.GCneHTBce ?? 'Alex Chen',
    h0NtaiGHO:
      testimonial2 ??
      props.h0NtaiGHO ??
      '\u201CJet transformed our entire workflow. We\xA0cut load times by\xA080% and our development team couldn\u2019t be\xA0happier.\u201D',
    KKdiRFJu2: image ?? props.KKdiRFJu2,
    Nmm1AYzfJ:
      testimonial ??
      props.Nmm1AYzfJ ??
      '\u201CMy shop now loads in under a second. Jet is the only tool I needed.\u201D',
    NnRAVynIX: role2 ?? props.NnRAVynIX ?? 'Founder @ Gropa',
    oGqNJ1s9K: color ?? props.oGqNJ1s9K ?? 'var(--token-70af50e6-b68b-4785-a006-3affe73027af, rgb(41, 194, 255))',
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? 'gXOOgW_0x',
    vrcKhHwBb: image2 ?? props.vrcKhHwBb,
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className,
    layoutId,
    variant,
    Nmm1AYzfJ,
    ELlerrEJz,
    BkVgYZ4LQ,
    KKdiRFJu2,
    oGqNJ1s9K,
    h0NtaiGHO,
    GCneHTBce,
    NnRAVynIX,
    vrcKhHwBb,
    BgC3EyFez,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'gXOOgW_0x',
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = []
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition
          value={transition1}
          {...addPropertyOverrides(
            {
              y4G8oqwNh: {
                value: transition2,
              },
              zhhN81oxS: {
                value: transition2,
              },
            },
            baseVariant,
            gestureVariant,
          )}
        >
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(scopingClassNames, 'framer-vy0o8s', className, classNames)}
            data-framer-name={'Start'}
            layoutDependency={layoutDependency}
            layoutId={'gXOOgW_0x'}
            ref={refBinding}
            style={{
              ...style,
            }}
            {...addPropertyOverrides(
              {
                y4G8oqwNh: {
                  'data-framer-name': 'Switch',
                },
                zhhN81oxS: {
                  'data-framer-name': 'Back',
                },
              },
              baseVariant,
              gestureVariant,
            )}
          >
            <ComponentViewportProvider
              height={300}
              width={`max(${componentViewport?.width || '100vw'}, 1px)`}
              y={(componentViewport?.y || 0) + (0 + ((componentViewport?.height || 300) - 0 - 300) / 2)}
              {...addPropertyOverrides(
                {
                  y4G8oqwNh: {
                    width: componentViewport?.width || '100vw',
                    y: (componentViewport?.y || 0) + -300,
                  },
                  zhhN81oxS: {
                    width: componentViewport?.width || '100vw',
                    y: (componentViewport?.y || 0) + -300,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <SmartComponentScopedContainer
                className={'framer-1vqxz4j-container'}
                data-framer-name={'1'}
                layoutDependency={layoutDependency}
                layoutId={'Pp8IDUoxt-container'}
                name={'1'}
                nodeId={'Pp8IDUoxt'}
                rendersWithMotion={true}
                scopeId={'W7wIBXQug'}
                style={{
                  filter: 'none',
                  opacity: 1,
                  WebkitFilter: 'none',
                }}
                variants={{
                  y4G8oqwNh: {
                    filter: 'blur(0px)',
                    opacity: 0,
                    WebkitFilter: 'blur(0px)',
                  },
                  zhhN81oxS: {
                    filter: 'none',
                    opacity: 1,
                    WebkitFilter: 'none',
                  },
                }}
              >
                {_jsx(stdin_default, {
                  a1AQ0lfUB: BkVgYZ4LQ,
                  height: '100%',
                  id: 'Pp8IDUoxt',
                  layoutId: 'Pp8IDUoxt',
                  name: '1',
                  rnxKgwYSX: toResponsiveImage(KKdiRFJu2),
                  style: {
                    height: '100%',
                    width: '100%',
                  },
                  uaBDeWXkh: ELlerrEJz,
                  width: '100%',
                  WRDXXfyCt: Nmm1AYzfJ,
                  YWe_iFc5i: oGqNJ1s9K,
                })}
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
            <ComponentViewportProvider
              height={300}
              width={componentViewport?.width || '100vw'}
              y={(componentViewport?.y || 0) + (componentViewport?.height || 300) - 0}
              {...addPropertyOverrides(
                {
                  y4G8oqwNh: {
                    width: `max(${componentViewport?.width || '100vw'}, 1px)`,
                    y: (componentViewport?.y || 0) + (0 + ((componentViewport?.height || 300) - 0 - 300) / 2),
                  },
                  zhhN81oxS: {
                    y: (componentViewport?.y || 0) + -300,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <SmartComponentScopedContainer
                className={'framer-1mryyip-container'}
                data-framer-name={'2'}
                layoutDependency={layoutDependency}
                layoutId={'Tjmfyo7ZA-container'}
                name={'2'}
                nodeId={'Tjmfyo7ZA'}
                rendersWithMotion={true}
                scopeId={'W7wIBXQug'}
                style={{
                  filter: 'blur(0px)',
                  opacity: 0,
                  WebkitFilter: 'blur(0px)',
                }}
                variants={{
                  y4G8oqwNh: {
                    opacity: 1,
                  },
                }}
              >
                {_jsx(stdin_default, {
                  a1AQ0lfUB: NnRAVynIX,
                  height: '100%',
                  id: 'Tjmfyo7ZA',
                  layoutId: 'Tjmfyo7ZA',
                  name: '2',
                  rnxKgwYSX: toResponsiveImage(vrcKhHwBb),
                  style: {
                    height: '100%',
                    width: '100%',
                  },
                  uaBDeWXkh: GCneHTBce,
                  width: '100%',
                  WRDXXfyCt: h0NtaiGHO,
                  YWe_iFc5i: BgC3EyFez,
                })}
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
            <ComponentViewportProvider
              height={300}
              width={componentViewport?.width || '100vw'}
              y={(componentViewport?.y || 0) + (componentViewport?.height || 300) - 0}
              {...addPropertyOverrides(
                {
                  zhhN81oxS: {
                    width: `max(${componentViewport?.width || '100vw'}, 1px)`,
                    y: (componentViewport?.y || 0) + (0 + ((componentViewport?.height || 300) - 0 - 300) / 2),
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <SmartComponentScopedContainer
                className={'framer-11lte9k-container'}
                data-framer-name={'1'}
                layoutDependency={layoutDependency}
                layoutId={'b7pUnjoZE-container'}
                name={'1'}
                nodeId={'b7pUnjoZE'}
                rendersWithMotion={true}
                scopeId={'W7wIBXQug'}
                style={{
                  filter: 'blur(0px)',
                  opacity: 0,
                  WebkitFilter: 'blur(0px)',
                }}
                variants={{
                  zhhN81oxS: {
                    opacity: 1,
                  },
                }}
              >
                {_jsx(stdin_default, {
                  a1AQ0lfUB: BkVgYZ4LQ,
                  height: '100%',
                  id: 'b7pUnjoZE',
                  layoutId: 'b7pUnjoZE',
                  name: '1',
                  rnxKgwYSX: toResponsiveImage(KKdiRFJu2),
                  style: {
                    height: '100%',
                    width: '100%',
                  },
                  uaBDeWXkh: ELlerrEJz,
                  width: '100%',
                  WRDXXfyCt: Nmm1AYzfJ,
                  YWe_iFc5i: oGqNJ1s9K,
                })}
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-AcMmK.framer-sgwene, .framer-AcMmK .framer-sgwene { display: block; }',
  '.framer-AcMmK.framer-vy0o8s { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 390px; }',
  '.framer-AcMmK .framer-1vqxz4j-container { flex: 1 0 0px; height: 300px; position: relative; width: 1px; z-index: 3; }',
  '.framer-AcMmK .framer-1mryyip-container, .framer-AcMmK .framer-11lte9k-container { bottom: -300px; flex: none; height: 300px; left: 0px; position: absolute; right: 0px; z-index: 3; }',
  '.framer-AcMmK.framer-v-c6hvu7 .framer-1vqxz4j-container, .framer-AcMmK.framer-v-eav2yx .framer-1vqxz4j-container { flex: none; left: 0px; position: absolute; right: 0px; top: -300px; width: unset; }',
  '.framer-AcMmK.framer-v-c6hvu7 .framer-1mryyip-container, .framer-AcMmK.framer-v-eav2yx .framer-11lte9k-container { bottom: unset; flex: 1 0 0px; left: unset; position: relative; right: unset; width: 1px; }',
  '.framer-AcMmK.framer-v-eav2yx .framer-1mryyip-container { bottom: unset; top: -300px; }',
]
var FramerW7wIBXQug = withCSS(Component, css, 'framer-AcMmK')
var stdin_default2 = FramerW7wIBXQug
FramerW7wIBXQug.displayName = 'Testimonial Cycler'
FramerW7wIBXQug.defaultProps = {
  height: 300,
  width: 390,
}
addPropertyControls(FramerW7wIBXQug, {
  variant: {
    options: ['gXOOgW_0x', 'y4G8oqwNh', 'zhhN81oxS'],
    optionTitles: ['Start', 'Switch', 'Back'],
    title: 'Variant',
    type: ControlType.Enum,
  },
  Nmm1AYzfJ: {
    defaultValue: '\u201CMy shop now loads in under a second. Jet is the only tool I needed.\u201D',
    displayTextArea: false,
    title: 'Testimonial',
    type: ControlType.String,
  },
  ELlerrEJz: {
    defaultValue: 'Luca Rossi',
    displayTextArea: false,
    title: 'Name',
    type: ControlType.String,
  },
  BkVgYZ4LQ: {
    defaultValue: 'E-commerce Owner',
    displayTextArea: false,
    title: 'Role',
    type: ControlType.String,
  },
  KKdiRFJu2: {
    title: 'Image',
    type: ControlType.ResponsiveImage,
  },
  oGqNJ1s9K: {
    defaultValue: 'var(--token-70af50e6-b68b-4785-a006-3affe73027af, rgb(41, 194, 255)) /* {"name":"Blue"} */',
    title: 'Color',
    type: ControlType.Color,
  },
  h0NtaiGHO: {
    defaultValue:
      '\u201CJet transformed our entire workflow. We\xA0cut load times by\xA080% and our development team couldn\u2019t be\xA0happier.\u201D',
    displayTextArea: false,
    title: 'Testimonial 2',
    type: ControlType.String,
  },
  GCneHTBce: {
    defaultValue: 'Alex Chen',
    displayTextArea: false,
    title: 'Name 2',
    type: ControlType.String,
  },
  NnRAVynIX: {
    defaultValue: 'Founder @ Gropa',
    displayTextArea: false,
    title: 'Role 2',
    type: ControlType.String,
  },
  vrcKhHwBb: {
    title: 'Image 2',
    type: ControlType.ResponsiveImage,
  },
  BgC3EyFez: {
    defaultValue: 'var(--token-1e61b8ec-fb03-4d71-8889-99c84f72af30, rgb(216, 92, 224)) /* {"name":"Pink"} */',
    title: 'Color 2',
    type: ControlType.Color,
  },
})
addFonts(
  FramerW7wIBXQug,
  [
    {
      explicitInter: true,
      fonts: [],
    },
    ...SmallTestimonialCardFonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// virtual:testimonial-cycler
import { WithFramerBreakpoints } from 'unframer'
import { jsx } from 'react/jsx-runtime'
var locales = []
var defaultResponsiveVariants = {
  base: 'gXOOgW_0x',
}
stdin_default2.Responsive = ({ locale, ...rest }) => {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints Component={stdin_default2} variants={defaultResponsiveVariants} {...rest} />
    </ContextProviders>
  )
}
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'}
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default2, {
        ...rest,
      })}
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default2)
export { ComponentWithRoot as default }
