// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project dfa04aa1c5bdec07 "Jet - SaaS Template (copy)", do not edit manually */
'use client'

import { Confetti } from './chunks/chunk-E2MHBRGR.js'
import './chunks/chunk-NMXRERF6.js'
import { stdin_default } from './chunks/chunk-HOQ3FAZW.js'
import { className, css, fonts } from './chunks/chunk-6NFSISF2.js'

// virtual:waitlist-form
import { Fragment as Fragment3 } from 'react'
import { ContextProviders } from 'unframer'

// /:https://framerusercontent.com/modules/lhovZstAJk48aaciqLMc/1MhTMzwwQRuzJ9IIgl1H/lncz8qZqS.js
import {
  jsx as _jsx2,
  jsxs as _jsxs2,
  Fragment as _Fragment,
} from 'react/jsx-runtime'
import {
  addFonts as addFonts2,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx as cx2,
  FormContainer,
  FormPlainTextInput,
  getFonts as getFonts2,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport as useComponentViewport2,
  useLocaleInfo as useLocaleInfo2,
  useOnVariantChange,
  useVariantState as useVariantState2,
  withCSS as withCSS2,
} from 'unframer'
import {
  LayoutGroup as LayoutGroup2,
  motion as motion2,
  MotionConfigContext as MotionConfigContext2,
} from 'unframer'
import * as React2 from 'react'
import { useRef as useRef2 } from 'react'

// /:https://framerusercontent.com/modules/S2HbgsVshzXmbAzcSsEZ/dbphtrRpEjJ9QdkhtPBb/DDFedjKAC.js
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime'
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from 'unframer'
import { LayoutGroup, motion, MotionConfigContext } from 'unframer'
import * as React from 'react'
import { useRef } from 'react'
var LoaderFonts = getFonts(stdin_default)
var LoaderWithFX = withFX(stdin_default)
var enabledGestures = {
  b7eOTPEdT: {
    hover: true,
  },
}
var cycleOrder = [
  'b7eOTPEdT',
  'KtJXuTrAP',
  'JsFnc46Fk',
  'cq4TYNeCx',
  'EYtyXzZeq',
]
var serializationHash = 'framer-P7oOA'
var variantClassNames = {
  b7eOTPEdT: 'framer-v-qmgsm0',
  cq4TYNeCx: 'framer-v-nsh1e8',
  EYtyXzZeq: 'framer-v-gohv4e',
  JsFnc46Fk: 'framer-v-uohzb4',
  KtJXuTrAP: 'framer-v-1bofamw',
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  )
  return nextOverrides
}
var transition1 = {
  bounce: 0,
  delay: 0,
  duration: 0.4,
  type: 'spring',
}
var transition2 = {
  delay: 0,
  duration: 0.5,
  ease: [0.44, 0, 0.56, 1],
  type: 'tween',
}
var animation = {
  opacity: 1,
  rotate: 360,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
}
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`
var transformTemplate2 = (_, t) => `translateY(-50%) ${t}`
var isSet = (value) => {
  if (Array.isArray(value)) return value.length > 0
  return value !== void 0 && value !== null && value !== ''
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  Default: 'b7eOTPEdT',
  Dot: 'EYtyXzZeq',
  Error: 'cq4TYNeCx',
  Loading: 'KtJXuTrAP',
  Success: 'JsFnc46Fk',
}
var getProps = ({
  additional,
  error,
  height,
  id,
  label,
  success,
  width,
  ...props
}) => {
  return {
    ...props,
    puP6A2dz_: additional ?? props.puP6A2dz_,
    SB93GG782: success ?? props.SB93GG782 ?? 'Thanks for your application!',
    SMZpJms0Q: label ?? props.SMZpJms0Q ?? 'Apply for',
    v5N8mGmrX: error ?? props.v5N8mGmrX ?? 'Something went wrong',
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? 'b7eOTPEdT',
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    SMZpJms0Q,
    puP6A2dz_,
    SB93GG782,
    v5N8mGmrX,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: 'b7eOTPEdT',
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const isDisplayed = () => {
    if (baseVariant === 'KtJXuTrAP') return true
    return false
  }
  const visible = isSet(puP6A2dz_)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.button
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              'framer-qmgsm0',
              className2,
              classNames,
            )}
            data-framer-name={'Default'}
            data-reset={'button'}
            draggable={'false'}
            layoutDependency={layoutDependency}
            layoutId={'b7eOTPEdT'}
            ref={refBinding}
            style={{
              backdropFilter: 'blur(2px)',
              backgroundColor:
                'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
              borderBottomLeftRadius: 20,
              borderBottomRightRadius: 20,
              borderTopLeftRadius: 20,
              borderTopRightRadius: 20,
              filter: 'none',
              WebkitBackdropFilter: 'blur(2px)',
              WebkitFilter: 'none',
              ...style,
            }}
            variants={{
              'b7eOTPEdT-hover': {
                filter: 'brightness(0.8)',
                WebkitFilter: 'brightness(0.8)',
              },
              cq4TYNeCx: {
                backgroundColor: 'rgba(219, 44, 44, 0.15)',
              },
              JsFnc46Fk: {
                backgroundColor: 'rgba(255, 255, 255, 0)',
              },
            }}
            {...addPropertyOverrides(
              {
                'b7eOTPEdT-hover': {
                  'data-framer-name': void 0,
                },
                cq4TYNeCx: {
                  'data-framer-name': 'Error',
                },
                EYtyXzZeq: {
                  'data-framer-name': 'Dot',
                },
                JsFnc46Fk: {
                  'data-framer-name': 'Success',
                },
                KtJXuTrAP: {
                  'data-framer-name': 'Loading',
                },
              },
              baseVariant,
              gestureVariant,
            )}
          >
            {isDisplayed() && (
              <LoaderWithFX
                __framer__loop={animation}
                __framer__loopEffectEnabled={true}
                __framer__loopPauseOffscreen={true}
                __framer__loopRepeatDelay={0}
                __framer__loopRepeatType={'loop'}
                __framer__loopTransition={transition2}
                __perspectiveFX={false}
                __smartComponentFX={true}
                __targetOpacity={0}
                animated={true}
                className={'framer-1ks31km'}
                layoutDependency={layoutDependency}
                layoutId={'RUU3Zske0'}
                style={{
                  '--13bnw74':
                    'var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))',
                  opacity: 0,
                }}
                transformTemplate={transformTemplate1}
                variants={{
                  KtJXuTrAP: {
                    opacity: 1,
                  },
                }}
                {...addPropertyOverrides(
                  {
                    KtJXuTrAP: {
                      __targetOpacity: 1,
                    },
                  },
                  baseVariant,
                  gestureVariant,
                )}
              />
            )}
            <motion.div
              className={'framer-atw89t'}
              data-framer-name={'Success'}
              layoutDependency={layoutDependency}
              layoutId={'ryRqIptNb'}
              style={{
                filter: 'blur(2px)',
                opacity: 0,
                scale: 0.9,
                WebkitFilter: 'blur(2px)',
              }}
              transformTemplate={transformTemplate1}
              variants={{
                JsFnc46Fk: {
                  filter: 'blur(0px)',
                  opacity: 1,
                  scale: 1,
                  WebkitFilter: 'blur(0px)',
                },
              }}
              {...addPropertyOverrides(
                {
                  JsFnc46Fk: {
                    transformTemplate: void 0,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <RichText
                __fromCanvasComponent={true}
                className={'framer-guq5gn'}
                data-framer-name={'Text'}
                fonts={['Inter']}
                layoutDependency={layoutDependency}
                layoutId={'l39ioVxkt'}
                style={{
                  '--extracted-r6o4lv':
                    'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))',
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline',
                }}
                text={SB93GG782}
                verticalAlignment={'top'}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.p
                    className={'framer-styles-preset-ujo3da'}
                    data-styles-preset={'sQrIs9_t0'}
                    style={{
                      '--framer-text-color':
                        'var(--extracted-r6o4lv, var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)))',
                    }}
                  >
                    {'Thanks for your application!'}
                  </motion.p>
                </React.Fragment>
              </RichText>
            </motion.div>
            <motion.div
              className={'framer-1xmenn2'}
              data-framer-name={'Error'}
              layoutDependency={layoutDependency}
              layoutId={'R_4MlO8Vq'}
              style={{
                filter: 'blur(2px)',
                opacity: 0,
                scale: 0.9,
                WebkitFilter: 'blur(2px)',
              }}
              transformTemplate={transformTemplate1}
              variants={{
                cq4TYNeCx: {
                  filter: 'blur(0px)',
                  opacity: 1,
                  scale: 1,
                  WebkitFilter: 'blur(0px)',
                },
              }}
              {...addPropertyOverrides(
                {
                  cq4TYNeCx: {
                    transformTemplate: void 0,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <RichText
                __fromCanvasComponent={true}
                className={'framer-hwzeqw'}
                data-framer-name={'Text'}
                fonts={['Inter']}
                layoutDependency={layoutDependency}
                layoutId={'uEmIec4Jw'}
                style={{
                  '--extracted-r6o4lv':
                    'var(--token-1e8433a6-dbc9-469b-bb1a-972dd419d298, rgb(219, 44, 44))',
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline',
                }}
                text={v5N8mGmrX}
                verticalAlignment={'top'}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.p
                    className={'framer-styles-preset-ujo3da'}
                    data-styles-preset={'sQrIs9_t0'}
                    style={{
                      '--framer-text-color':
                        'var(--extracted-r6o4lv, var(--token-1e8433a6-dbc9-469b-bb1a-972dd419d298, rgb(219, 44, 44)))',
                    }}
                  >
                    {'Something went wrong'}
                  </motion.p>
                </React.Fragment>
              </RichText>
            </motion.div>
            <motion.div
              className={'framer-nkutpy'}
              data-framer-name={'Label'}
              layoutDependency={layoutDependency}
              layoutId={'oXXceo2Ko'}
              style={{
                filter: 'none',
                opacity: 1,
                scale: 1,
                WebkitFilter: 'none',
              }}
              variants={{
                'b7eOTPEdT-hover': {
                  filter: 'none',
                  opacity: 1,
                  scale: 1,
                  WebkitFilter: 'none',
                },
                cq4TYNeCx: {
                  filter: 'blur(2px)',
                  opacity: 0,
                  scale: 1.1,
                  WebkitFilter: 'blur(2px)',
                },
                EYtyXzZeq: {
                  filter: 'blur(2px)',
                  opacity: 0,
                  scale: 1.1,
                  WebkitFilter: 'blur(2px)',
                },
                JsFnc46Fk: {
                  filter: 'blur(2px)',
                  opacity: 0,
                  scale: 1.1,
                  WebkitFilter: 'blur(2px)',
                },
                KtJXuTrAP: {
                  filter: 'blur(2px)',
                  opacity: 0,
                  scale: 1.1,
                  WebkitFilter: 'blur(2px)',
                },
              }}
              {...addPropertyOverrides(
                {
                  cq4TYNeCx: {
                    transformTemplate: transformTemplate1,
                  },
                  JsFnc46Fk: {
                    transformTemplate: transformTemplate2,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              <RichText
                __fromCanvasComponent={true}
                className={'framer-1m7oxp6'}
                fonts={['Inter']}
                layoutDependency={layoutDependency}
                layoutId={'Hk7Q00Vrg'}
                style={{
                  '--extracted-r6o4lv':
                    'var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))',
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline',
                }}
                text={SMZpJms0Q}
                verticalAlignment={'top'}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.p
                    className={'framer-styles-preset-ujo3da'}
                    data-styles-preset={'sQrIs9_t0'}
                    style={{
                      '--framer-text-color':
                        'var(--extracted-r6o4lv, var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0)))',
                    }}
                  >
                    {'Apply for '}
                  </motion.p>
                </React.Fragment>
              </RichText>
              {visible && (
                <RichText
                  __fromCanvasComponent={true}
                  className={'framer-yna080'}
                  data-framer-name={'Additional'}
                  fonts={['Inter']}
                  layoutDependency={layoutDependency}
                  layoutId={'ixuBEVFZz'}
                  style={{
                    '--extracted-r6o4lv':
                      'var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0))',
                    '--framer-link-text-color': 'rgb(0, 153, 255)',
                    '--framer-link-text-decoration': 'underline',
                  }}
                  text={puP6A2dz_}
                  verticalAlignment={'top'}
                  withExternalLayout={true}
                >
                  <React.Fragment>
                    <motion.p
                      className={'framer-styles-preset-ujo3da'}
                      data-styles-preset={'sQrIs9_t0'}
                      style={{
                        '--framer-text-color':
                          'var(--extracted-r6o4lv, var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, rgb(0, 0, 0)))',
                      }}
                    >
                      {'Apply for'}
                    </motion.p>
                  </React.Fragment>
                </RichText>
              )}
            </motion.div>
            <motion.div
              className={'framer-1abkj4w'}
              data-framer-name={'BG'}
              layoutDependency={layoutDependency}
              layoutId={'OK4Q3x2f1'}
              style={{
                backgroundColor:
                  'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))',
                borderBottomLeftRadius: 100,
                borderBottomRightRadius: 100,
                borderTopLeftRadius: 100,
                borderTopRightRadius: 100,
                opacity: 0,
              }}
              variants={{
                JsFnc46Fk: {
                  opacity: 0.1,
                },
              }}
            />
          </motion.button>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css2 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-P7oOA.framer-1y56j1k, .framer-P7oOA .framer-1y56j1k { display: block; }',
  '.framer-P7oOA.framer-qmgsm0 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 40px; justify-content: center; overflow: hidden; padding: 0px 18px 0px 18px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }',
  '.framer-P7oOA .framer-1ks31km { flex: none; height: var(--framer-aspect-ratio-supported, 24px); left: 50%; position: absolute; top: 50%; width: 24px; z-index: 5; }',
  '.framer-P7oOA .framer-atw89t, .framer-P7oOA .framer-1xmenn2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 50%; width: min-content; z-index: 1; }',
  '.framer-P7oOA .framer-guq5gn, .framer-P7oOA .framer-hwzeqw, .framer-P7oOA .framer-1m7oxp6, .framer-P7oOA .framer-yna080 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-P7oOA .framer-nkutpy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 3.5px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }',
  '.framer-P7oOA .framer-1abkj4w { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 0; }',
  '.framer-P7oOA.framer-v-uohzb4.framer-qmgsm0, .framer-P7oOA.framer-v-nsh1e8.framer-qmgsm0 { cursor: default; }',
  '.framer-P7oOA.framer-v-uohzb4 .framer-atw89t, .framer-P7oOA.framer-v-nsh1e8 .framer-1xmenn2 { left: unset; position: relative; top: unset; }',
  '.framer-P7oOA.framer-v-uohzb4 .framer-nkutpy { left: 55px; position: absolute; top: 50%; }',
  '.framer-P7oOA.framer-v-nsh1e8 .framer-nkutpy { left: 50%; position: absolute; top: 50%; z-index: 1; }',
  '.framer-P7oOA.framer-v-gohv4e.framer-qmgsm0 { width: 40px; }',
  ...css,
]
var FramerDDFedjKAC = withCSS(Component, css2, 'framer-P7oOA')
var stdin_default2 = FramerDDFedjKAC
FramerDDFedjKAC.displayName = 'Submit Form Button'
FramerDDFedjKAC.defaultProps = {
  height: 40,
  width: 98,
}
addPropertyControls(FramerDDFedjKAC, {
  variant: {
    options: ['b7eOTPEdT', 'KtJXuTrAP', 'JsFnc46Fk', 'cq4TYNeCx', 'EYtyXzZeq'],
    optionTitles: ['Default', 'Loading', 'Success', 'Error', 'Dot'],
    title: 'Variant',
    type: ControlType.Enum,
  },
  SMZpJms0Q: {
    defaultValue: 'Apply for',
    displayTextArea: false,
    title: 'Label',
    type: ControlType.String,
  },
  puP6A2dz_: {
    defaultValue: '',
    title: 'Additional',
    type: ControlType.String,
  },
  SB93GG782: {
    defaultValue: 'Thanks for your application!',
    placeholder: '',
    title: 'Success',
    type: ControlType.String,
  },
  v5N8mGmrX: {
    defaultValue: 'Something went wrong',
    description: '',
    title: 'Error',
    type: ControlType.String,
  },
})
addFonts(
  FramerDDFedjKAC,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
          url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
          url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+1F00-1FFF',
          url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange: 'U+0370-03FF',
          url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
          url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
          url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
          weight: '400',
        },
        {
          family: 'Inter',
          source: 'framer',
          style: 'normal',
          unicodeRange:
            'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
          url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
          weight: '400',
        },
      ],
    },
    ...LoaderFonts,
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// /:https://framerusercontent.com/modules/lhovZstAJk48aaciqLMc/1MhTMzwwQRuzJ9IIgl1H/lncz8qZqS.js
var SubmitFormButtonFonts = getFonts2(stdin_default2)
var ConfettiFonts = getFonts2(Confetti)
var cycleOrder2 = ['oWEros5wR', 'cGnEhrzcw', 'QVokkkwj5']
var serializationHash2 = 'framer-SJmho'
var variantClassNames2 = {
  cGnEhrzcw: 'framer-v-1calhdc',
  oWEros5wR: 'framer-v-1wutwn6',
  QVokkkwj5: 'framer-v-j7dh35',
}
function addPropertyOverrides2(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant]),
  )
  return nextOverrides
}
var transition12 = {
  bounce: 0,
  delay: 0,
  duration: 0.4,
  type: 'spring',
}
var transition22 = {
  bounce: 0,
  delay: 0.05,
  duration: 0.4,
  type: 'spring',
}
var transition3 = {
  bounce: 0,
  delay: 0.1,
  duration: 0.4,
  type: 'spring',
}
var Transition2 = ({ value, children }) => {
  const config = React2.useContext(MotionConfigContext2)
  const transition = value ?? config.transition
  const contextValue = React2.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)],
  )
  return (
    <MotionConfigContext2.Provider value={contextValue}>
      {children}
    </MotionConfigContext2.Provider>
  )
}
var transformTemplate12 = (_, t) => `translateY(-50%) ${t}`
var formVariants = (form, variants, currentVariant) => {
  switch (form.state) {
    case 'success':
      return variants.success ?? currentVariant
    case 'pending':
      return variants.pending ?? currentVariant
    case 'error':
      return variants.error ?? currentVariant
    case 'incomplete':
      return variants.incomplete ?? currentVariant
  }
}
var Variants2 = motion2.create(React2.Fragment)
var humanReadableVariantMap2 = {
  'Succes (1)': 'cGnEhrzcw',
  'Success (2)': 'QVokkkwj5',
  Default: 'oWEros5wR',
}
var getProps2 = ({ height, id, label, width, ...props }) => {
  return {
    ...props,
    skL1oWl_l: label ?? props.skL1oWl_l ?? 'Join now',
    variant:
      humanReadableVariantMap2[props.variant] ?? props.variant ?? 'oWEros5wR',
  }
}
var createLayoutDependency2 = (props, variants) => {
  if (props.layoutDependency) return variants.join('-') + props.layoutDependency
  return variants.join('-')
}
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
  const fallbackRef = useRef2(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React2.useId()
  const { activeLocale, setLocale } = useLocaleInfo2()
  const componentViewport = useComponentViewport2()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    skL1oWl_l,
    ...restProps
  } = getProps2(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState2({
    cycleOrder: cycleOrder2,
    defaultVariant: 'oWEros5wR',
    ref: refBinding,
    variant,
    variantClassNames: variantClassNames2,
  })
  const layoutDependency = createLayoutDependency2(props, variants)
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)
  const onAppeartp7v2p = activeVariantCallback(async (...args) => {
    await delay(() => setVariant('QVokkkwj5', true), 250)
  })
  const onSuccesskxd05a = activeVariantCallback(async (...args) => {
    setVariant('cGnEhrzcw')
  })
  useOnVariantChange(baseVariant, {
    cGnEhrzcw: onAppeartp7v2p,
  })
  const sharedStyleClassNames = []
  const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames)
  const isDisplayed = () => {
    if (baseVariant === 'QVokkkwj5') return true
    return false
  }
  return (
    <LayoutGroup2 id={layoutId ?? defaultLayoutId}>
      <Variants2 animate={variants} initial={false}>
        <Transition2 value={transition12}>
          <motion2.div
            {...restProps}
            {...gestureHandlers}
            className={cx2(
              scopingClassNames,
              'framer-1wutwn6',
              className2,
              classNames,
            )}
            data-framer-name={'Default'}
            layoutDependency={layoutDependency}
            layoutId={'oWEros5wR'}
            ref={refBinding}
            style={{
              backdropFilter: 'blur(2px)',
              backgroundColor: 'rgba(0, 0, 0, 0)',
              borderBottomLeftRadius: 100,
              borderBottomRightRadius: 100,
              borderTopLeftRadius: 100,
              borderTopRightRadius: 100,
              WebkitBackdropFilter: 'blur(2px)',
              ...style,
            }}
            variants={{
              QVokkkwj5: {
                backgroundColor: 'rgba(0, 0, 0, 0.01)',
              },
            }}
            {...addPropertyOverrides2(
              {
                cGnEhrzcw: {
                  'data-framer-name': 'Succes (1)',
                  'data-highlight': true,
                },
                QVokkkwj5: {
                  'data-framer-name': 'Success (2)',
                },
              },
              baseVariant,
              gestureVariant,
            )}
          >
            <FormContainer
              action={
                'https://api.framer.com/forms/v1/forms/a838b13d-4495-43f7-ba24-fd42090d36c1/submit'
              }
              className={'framer-uk1nxd'}
              data-highlight={true}
              layoutDependency={layoutDependency}
              layoutId={'fsvSLNsFB'}
              nodeId={'fsvSLNsFB'}
              onSuccess={onSuccesskxd05a}
              {...addPropertyOverrides2(
                {
                  cGnEhrzcw: {
                    'data-highlight': void 0,
                    onSuccess: void 0,
                  },
                  QVokkkwj5: {
                    'data-highlight': void 0,
                    onSuccess: void 0,
                  },
                },
                baseVariant,
                gestureVariant,
              )}
            >
              {(formState) => (
                <_Fragment>
                  <motion2.div
                    className={'framer-11cuiav'}
                    data-framer-name={'Fields'}
                    layoutDependency={layoutDependency}
                    layoutId={'KE6eSjA0x'}
                  >
                    <motion2.div
                      className={'framer-1cv2vq1'}
                      data-framer-name={'Wrap'}
                      layoutDependency={layoutDependency}
                      layoutId={'qGoXJ0Pys'}
                      style={{
                        rotateX: 90,
                      }}
                    >
                      <Transition2
                        {...addPropertyOverrides2(
                          {
                            cGnEhrzcw: {
                              value: transition22,
                            },
                            QVokkkwj5: {
                              value: transition3,
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        )}
                      >
                        <motion2.label
                          className={'framer-fc65fn'}
                          data-framer-name={'Form Field'}
                          layoutDependency={layoutDependency}
                          layoutId={'t7uG2IqDk'}
                          style={{
                            opacity: 1,
                            rotateX: -90,
                            z: 0,
                          }}
                          variants={{
                            cGnEhrzcw: {
                              opacity: 0,
                              z: 20,
                            },
                            QVokkkwj5: {
                              opacity: 0,
                              z: 20,
                            },
                          }}
                        >
                          <FormPlainTextInput
                            className={'framer-c8fcm0'}
                            inputName={'Email'}
                            layoutDependency={layoutDependency}
                            layoutId={'KcWtR549V'}
                            placeholder={'Enter your email'}
                            required={true}
                            style={{
                              '--framer-input-background':
                                'var(--token-fa07d228-afbe-4fad-9a44-2fb0dadd2a5e, rgb(23, 23, 23))',
                              '--framer-input-border-radius-bottom-left':
                                '38px',
                              '--framer-input-border-radius-bottom-right':
                                '38px',
                              '--framer-input-border-radius-top-left': '38px',
                              '--framer-input-border-radius-top-right': '38px',
                              '--framer-input-box-shadow':
                                '0px 3px 6px 0px var(--token-54d5892b-0224-424e-b224-359f05491e1f, rgba(0, 0, 0, 0.75)), inset 0px 1px 0px 0px var(--token-22e7e14f-1f70-49cd-ae98-e88c20549e6b, rgba(255, 255, 255, 0.03)), inset 0px -1px 0px 0px var(--token-54d5892b-0224-424e-b224-359f05491e1f, rgba(0, 0, 0, 0.75))',
                              '--framer-input-font-color':
                                'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                              '--framer-input-icon-color': 'rgb(153, 153, 153)',
                              '--framer-input-placeholder-color':
                                'var(--token-311dfa1b-5054-44c6-8b55-ece1611bbe6a, rgba(255, 255, 255, 0.3))',
                            }}
                            type={'email'}
                          />
                        </motion2.label>
                      </Transition2>
                      <motion2.div
                        className={'framer-60bcly'}
                        data-framer-name={'Button Wrap'}
                        layoutDependency={layoutDependency}
                        layoutId={'G8lYHuUIT'}
                        style={{
                          rotateX: -90,
                        }}
                        {...addPropertyOverrides2(
                          {
                            QVokkkwj5: {
                              transformTemplate: transformTemplate12,
                            },
                          },
                          baseVariant,
                          gestureVariant,
                        )}
                      >
                        <ComponentViewportProvider
                          height={40}
                          {...addPropertyOverrides2(
                            {
                              QVokkkwj5: {
                                width: `max(max(${componentViewport?.width || '100vw'}, 200px), 1px)`,
                              },
                            },
                            baseVariant,
                            gestureVariant,
                          )}
                        >
                          <SmartComponentScopedContainer
                            className={'framer-1r4qej5-container'}
                            layoutDependency={layoutDependency}
                            layoutId={'uAu0XfBYf-container'}
                            nodeId={'uAu0XfBYf'}
                            rendersWithMotion={true}
                            scopeId={'lncz8qZqS'}
                          >
                            {_jsx2(stdin_default2, {
                              height: '100%',
                              id: 'uAu0XfBYf',
                              layoutId: 'uAu0XfBYf',
                              puP6A2dz_: '',
                              SB93GG782: "You're on the waitlist!",
                              SMZpJms0Q: skL1oWl_l,
                              type: 'submit',
                              v5N8mGmrX: 'Something went wrong',
                              variant: formVariants(
                                formState,
                                {
                                  error: 'cq4TYNeCx',
                                  pending: 'KtJXuTrAP',
                                },
                                'b7eOTPEdT',
                              ),
                              width: '100%',
                              ...addPropertyOverrides2(
                                {
                                  cGnEhrzcw: {
                                    variant: formVariants(
                                      formState,
                                      {
                                        error: 'cq4TYNeCx',
                                        pending: 'KtJXuTrAP',
                                      },
                                      'KtJXuTrAP',
                                    ),
                                  },
                                  QVokkkwj5: {
                                    style: {
                                      width: '100%',
                                    },
                                    variant: formVariants(
                                      formState,
                                      {
                                        error: 'cq4TYNeCx',
                                        pending: 'KtJXuTrAP',
                                      },
                                      'JsFnc46Fk',
                                    ),
                                  },
                                },
                                baseVariant,
                                gestureVariant,
                              ),
                            })}
                          </SmartComponentScopedContainer>
                        </ComponentViewportProvider>
                      </motion2.div>
                    </motion2.div>
                  </motion2.div>
                </_Fragment>
              )}
            </FormContainer>
            {isDisplayed() && (
              <ComponentViewportProvider>
                <SmartComponentScopedContainer
                  className={'framer-14mt767-container'}
                  isAuthoredByUser={true}
                  isModuleExternal={true}
                  layoutDependency={layoutDependency}
                  layoutId={'NAXuYS70F-container'}
                  nodeId={'NAXuYS70F'}
                  rendersWithMotion={true}
                  scopeId={'lncz8qZqS'}
                >
                  <Confetti
                    amount={30}
                    color={{
                      colors: [
                        'var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197))',
                        'var(--token-4fef9130-aa55-4351-8ed5-cfba481137a7, rgb(255, 255, 255))',
                      ],
                      mode: 'Multi',
                      singleColor: 'rgb(32, 96, 223)',
                    }}
                    coverArea={360}
                    delayInSeconds={0.1}
                    explosion={'M'}
                    height={'100%'}
                    id={'NAXuYS70F'}
                    layoutId={'NAXuYS70F'}
                    style={{
                      height: '100%',
                      width: '100%',
                    }}
                    width={'100%'}
                  />
                </SmartComponentScopedContainer>
              </ComponentViewportProvider>
            )}
          </motion2.div>
        </Transition2>
      </Variants2>
    </LayoutGroup2>
  )
})
var css3 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-SJmho.framer-semwym, .framer-SJmho .framer-semwym { display: block; }',
  '.framer-SJmho.framer-1wutwn6 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 320px; }',
  '.framer-SJmho .framer-uk1nxd { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 4; }',
  '.framer-SJmho .framer-11cuiav { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 20px 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 0; }',
  '.framer-SJmho .framer-1cv2vq1 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-width: 200px; overflow: visible; padding: 0px; position: relative; transform-style: preserve-3d; width: 1px; }',
  '.framer-SJmho .framer-fc65fn { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1px; }',
  '.framer-SJmho .framer-c8fcm0 { --framer-input-focused-box-shadow: 0px 0px 0px 2px var(--token-bb3f9735-47c4-4ac2-b002-c5446021aee6, #000000), 0px 0px 0px 3px var(--token-19e7a84f-9c9f-4761-ac3b-54ec81f5f8e0, rgb(0, 230, 197)); --framer-input-font-family: "Geist"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 14px; --framer-input-font-weight: 400; --framer-input-padding: 12px 18px 12px 18px; --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }',
  '.framer-SJmho .framer-60bcly { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }',
  '.framer-SJmho .framer-1r4qej5-container { flex: none; height: auto; position: relative; width: auto; z-index: 3; }',
  '.framer-SJmho .framer-14mt767-container { flex: none; height: 10px; left: calc(50.00000000000002% - 10px / 2); position: absolute; top: calc(51.21951219512197% - 10px / 2); width: 10px; z-index: 4; }',
  '.framer-SJmho.framer-v-j7dh35 .framer-uk1nxd { pointer-events: none; }',
  '.framer-SJmho.framer-v-j7dh35 .framer-60bcly { left: 0px; position: absolute; right: 0px; top: 0%; width: unset; z-index: 1; }',
  '.framer-SJmho.framer-v-j7dh35 .framer-1r4qej5-container { flex: 1 0 0px; width: 1px; }',
]
var Framerlncz8qZqS = withCSS2(Component2, css3, 'framer-SJmho')
var stdin_default3 = Framerlncz8qZqS
Framerlncz8qZqS.displayName = 'Waitlist Form'
Framerlncz8qZqS.defaultProps = {
  height: 41,
  width: 320,
}
addPropertyControls2(Framerlncz8qZqS, {
  variant: {
    options: ['oWEros5wR', 'cGnEhrzcw', 'QVokkkwj5'],
    optionTitles: ['Default', 'Succes (1)', 'Success (2)'],
    title: 'Variant',
    type: ControlType2.Enum,
  },
  skL1oWl_l: {
    defaultValue: 'Join now',
    displayTextArea: false,
    title: 'Label',
    type: ControlType2.String,
  },
})
addFonts2(
  Framerlncz8qZqS,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: 'Geist',
          source: 'google',
          style: 'normal',
          url: 'https://fonts.gstatic.com/s/geist/v3/gyBhhwUxId8gMGYQMKR3pzfaWI_RnOM4mJPby1QNtA.woff2',
          weight: '400',
        },
      ],
    },
    ...SubmitFormButtonFonts,
    ...ConfettiFonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  },
)

// virtual:waitlist-form
import { WithFramerBreakpoints } from 'unframer'
import { jsx } from 'react/jsx-runtime'
var locales = []
var defaultResponsiveVariants = {
  base: 'oWEros5wR',
}
stdin_default3.Responsive = ({ locale, ...rest }) => {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={
        'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default3}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={{
        Agq1L2jDe: {
          path: '/careers/:slug',
        },
        J_r8CT7G7: {
          path: '/about',
        },
        SOf0RbDE_: {
          path: '/blog',
        },
        TQDjkQC2A: {
          path: '/contact',
        },
        YBTUYW5mq: {
          path: '/pricing',
        },
        a5CCfdDiy: {
          path: '/updates/:slug',
        },
        augiA20Il: {
          path: '/',
        },
        cpP7I9WGp: {
          path: '/404',
        },
        e9YIc4Uv5: {
          path: '/waitlist',
        },
        inNalAASs: {
          path: '/blog/:slug',
        },
        ixIXvnG3U: {
          path: '/legal/:slug',
        },
        rX7FOhQc0: {
          path: '/updates',
        },
        so5jTiDIE: {
          path: '/careers',
        },
      }}
      framerSiteId={
        'dfa04aa1c5bdec07246cce5cf5bdd608b64f5245b2256932daafbe1cb51c98be'
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default3, {
        ...rest,
      })}
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default3)
export { ComponentWithRoot as default }
